// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: binlog.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_binlog_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_binlog_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3018000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3018000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_binlog_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_binlog_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_binlog_2eproto;
namespace baikaldb {
namespace pb {
class Binlog;
struct BinlogDefaultTypeInternal;
extern BinlogDefaultTypeInternal _Binlog_default_instance_;
class PrewriteValue;
struct PrewriteValueDefaultTypeInternal;
extern PrewriteValueDefaultTypeInternal _PrewriteValue_default_instance_;
class TableMutation;
struct TableMutationDefaultTypeInternal;
extern TableMutationDefaultTypeInternal _TableMutation_default_instance_;
}  // namespace pb
}  // namespace baikaldb
PROTOBUF_NAMESPACE_OPEN
template<> ::baikaldb::pb::Binlog* Arena::CreateMaybeMessage<::baikaldb::pb::Binlog>(Arena*);
template<> ::baikaldb::pb::PrewriteValue* Arena::CreateMaybeMessage<::baikaldb::pb::PrewriteValue>(Arena*);
template<> ::baikaldb::pb::TableMutation* Arena::CreateMaybeMessage<::baikaldb::pb::TableMutation>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace baikaldb {
namespace pb {

enum BinlogType : int {
  PREWRITE = 0,
  COMMIT = 1,
  ROLLBACK = 2,
  DDL = 3,
  FAKE = 4
};
bool BinlogType_IsValid(int value);
constexpr BinlogType BinlogType_MIN = PREWRITE;
constexpr BinlogType BinlogType_MAX = FAKE;
constexpr int BinlogType_ARRAYSIZE = BinlogType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* BinlogType_descriptor();
template<typename T>
inline const std::string& BinlogType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, BinlogType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function BinlogType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    BinlogType_descriptor(), enum_t_value);
}
inline bool BinlogType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, BinlogType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<BinlogType>(
    BinlogType_descriptor(), name, value);
}
enum MutationType : int {
  INSERT = 0,
  UPDATE = 1,
  DELETE = 2
};
bool MutationType_IsValid(int value);
constexpr MutationType MutationType_MIN = INSERT;
constexpr MutationType MutationType_MAX = DELETE;
constexpr int MutationType_ARRAYSIZE = MutationType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MutationType_descriptor();
template<typename T>
inline const std::string& MutationType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MutationType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MutationType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MutationType_descriptor(), enum_t_value);
}
inline bool MutationType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MutationType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MutationType>(
    MutationType_descriptor(), name, value);
}
// ===================================================================

class Binlog final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:baikaldb.pb.Binlog) */ {
 public:
  inline Binlog() : Binlog(nullptr) {}
  ~Binlog() override;
  explicit constexpr Binlog(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Binlog(const Binlog& from);
  Binlog(Binlog&& from) noexcept
    : Binlog() {
    *this = ::std::move(from);
  }

  inline Binlog& operator=(const Binlog& from) {
    CopyFrom(from);
    return *this;
  }
  inline Binlog& operator=(Binlog&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Binlog& default_instance() {
    return *internal_default_instance();
  }
  static inline const Binlog* internal_default_instance() {
    return reinterpret_cast<const Binlog*>(
               &_Binlog_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Binlog& a, Binlog& b) {
    a.Swap(&b);
  }
  inline void Swap(Binlog* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Binlog* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Binlog* New() const final {
    return new Binlog();
  }

  Binlog* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Binlog>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Binlog& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Binlog& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Binlog* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "baikaldb.pb.Binlog";
  }
  protected:
  explicit Binlog(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPrewriteKeyFieldNumber = 4,
    kDdlQueryFieldNumber = 6,
    kStmtsFieldNumber = 7,
    kPrewriteValueFieldNumber = 5,
    kStartTsFieldNumber = 2,
    kCommitTsFieldNumber = 3,
    kPartitionKeyFieldNumber = 8,
    kTypeFieldNumber = 1,
  };
  // optional bytes prewrite_key = 4;
  bool has_prewrite_key() const;
  private:
  bool _internal_has_prewrite_key() const;
  public:
  void clear_prewrite_key();
  const std::string& prewrite_key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_prewrite_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_prewrite_key();
  PROTOBUF_MUST_USE_RESULT std::string* release_prewrite_key();
  void set_allocated_prewrite_key(std::string* prewrite_key);
  private:
  const std::string& _internal_prewrite_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_prewrite_key(const std::string& value);
  std::string* _internal_mutable_prewrite_key();
  public:

  // optional bytes ddl_query = 6;
  bool has_ddl_query() const;
  private:
  bool _internal_has_ddl_query() const;
  public:
  void clear_ddl_query();
  const std::string& ddl_query() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ddl_query(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ddl_query();
  PROTOBUF_MUST_USE_RESULT std::string* release_ddl_query();
  void set_allocated_ddl_query(std::string* ddl_query);
  private:
  const std::string& _internal_ddl_query() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ddl_query(const std::string& value);
  std::string* _internal_mutable_ddl_query();
  public:

  // optional bytes stmts = 7;
  bool has_stmts() const;
  private:
  bool _internal_has_stmts() const;
  public:
  void clear_stmts();
  const std::string& stmts() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_stmts(ArgT0&& arg0, ArgT... args);
  std::string* mutable_stmts();
  PROTOBUF_MUST_USE_RESULT std::string* release_stmts();
  void set_allocated_stmts(std::string* stmts);
  private:
  const std::string& _internal_stmts() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_stmts(const std::string& value);
  std::string* _internal_mutable_stmts();
  public:

  // optional .baikaldb.pb.PrewriteValue prewrite_value = 5;
  bool has_prewrite_value() const;
  private:
  bool _internal_has_prewrite_value() const;
  public:
  void clear_prewrite_value();
  const ::baikaldb::pb::PrewriteValue& prewrite_value() const;
  PROTOBUF_MUST_USE_RESULT ::baikaldb::pb::PrewriteValue* release_prewrite_value();
  ::baikaldb::pb::PrewriteValue* mutable_prewrite_value();
  void set_allocated_prewrite_value(::baikaldb::pb::PrewriteValue* prewrite_value);
  private:
  const ::baikaldb::pb::PrewriteValue& _internal_prewrite_value() const;
  ::baikaldb::pb::PrewriteValue* _internal_mutable_prewrite_value();
  public:
  void unsafe_arena_set_allocated_prewrite_value(
      ::baikaldb::pb::PrewriteValue* prewrite_value);
  ::baikaldb::pb::PrewriteValue* unsafe_arena_release_prewrite_value();

  // optional int64 start_ts = 2;
  bool has_start_ts() const;
  private:
  bool _internal_has_start_ts() const;
  public:
  void clear_start_ts();
  ::PROTOBUF_NAMESPACE_ID::int64 start_ts() const;
  void set_start_ts(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_start_ts() const;
  void _internal_set_start_ts(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // optional int64 commit_ts = 3;
  bool has_commit_ts() const;
  private:
  bool _internal_has_commit_ts() const;
  public:
  void clear_commit_ts();
  ::PROTOBUF_NAMESPACE_ID::int64 commit_ts() const;
  void set_commit_ts(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_commit_ts() const;
  void _internal_set_commit_ts(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // optional uint64 partition_key = 8;
  bool has_partition_key() const;
  private:
  bool _internal_has_partition_key() const;
  public:
  void clear_partition_key();
  ::PROTOBUF_NAMESPACE_ID::uint64 partition_key() const;
  void set_partition_key(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_partition_key() const;
  void _internal_set_partition_key(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional .baikaldb.pb.BinlogType type = 1;
  bool has_type() const;
  private:
  bool _internal_has_type() const;
  public:
  void clear_type();
  ::baikaldb::pb::BinlogType type() const;
  void set_type(::baikaldb::pb::BinlogType value);
  private:
  ::baikaldb::pb::BinlogType _internal_type() const;
  void _internal_set_type(::baikaldb::pb::BinlogType value);
  public:

  // @@protoc_insertion_point(class_scope:baikaldb.pb.Binlog)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr prewrite_key_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ddl_query_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr stmts_;
  ::baikaldb::pb::PrewriteValue* prewrite_value_;
  ::PROTOBUF_NAMESPACE_ID::int64 start_ts_;
  ::PROTOBUF_NAMESPACE_ID::int64 commit_ts_;
  ::PROTOBUF_NAMESPACE_ID::uint64 partition_key_;
  int type_;
  friend struct ::TableStruct_binlog_2eproto;
};
// -------------------------------------------------------------------

class PrewriteValue final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:baikaldb.pb.PrewriteValue) */ {
 public:
  inline PrewriteValue() : PrewriteValue(nullptr) {}
  ~PrewriteValue() override;
  explicit constexpr PrewriteValue(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PrewriteValue(const PrewriteValue& from);
  PrewriteValue(PrewriteValue&& from) noexcept
    : PrewriteValue() {
    *this = ::std::move(from);
  }

  inline PrewriteValue& operator=(const PrewriteValue& from) {
    CopyFrom(from);
    return *this;
  }
  inline PrewriteValue& operator=(PrewriteValue&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PrewriteValue& default_instance() {
    return *internal_default_instance();
  }
  static inline const PrewriteValue* internal_default_instance() {
    return reinterpret_cast<const PrewriteValue*>(
               &_PrewriteValue_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PrewriteValue& a, PrewriteValue& b) {
    a.Swap(&b);
  }
  inline void Swap(PrewriteValue* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PrewriteValue* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PrewriteValue* New() const final {
    return new PrewriteValue();
  }

  PrewriteValue* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PrewriteValue>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PrewriteValue& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const PrewriteValue& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PrewriteValue* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "baikaldb.pb.PrewriteValue";
  }
  protected:
  explicit PrewriteValue(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMutationsFieldNumber = 2,
    kSchemaVersionFieldNumber = 1,
  };
  // repeated .baikaldb.pb.TableMutation mutations = 2;
  int mutations_size() const;
  private:
  int _internal_mutations_size() const;
  public:
  void clear_mutations();
  ::baikaldb::pb::TableMutation* mutable_mutations(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::baikaldb::pb::TableMutation >*
      mutable_mutations();
  private:
  const ::baikaldb::pb::TableMutation& _internal_mutations(int index) const;
  ::baikaldb::pb::TableMutation* _internal_add_mutations();
  public:
  const ::baikaldb::pb::TableMutation& mutations(int index) const;
  ::baikaldb::pb::TableMutation* add_mutations();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::baikaldb::pb::TableMutation >&
      mutations() const;

  // optional int64 schema_version = 1;
  bool has_schema_version() const;
  private:
  bool _internal_has_schema_version() const;
  public:
  void clear_schema_version();
  ::PROTOBUF_NAMESPACE_ID::int64 schema_version() const;
  void set_schema_version(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_schema_version() const;
  void _internal_set_schema_version(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:baikaldb.pb.PrewriteValue)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::baikaldb::pb::TableMutation > mutations_;
  ::PROTOBUF_NAMESPACE_ID::int64 schema_version_;
  friend struct ::TableStruct_binlog_2eproto;
};
// -------------------------------------------------------------------

class TableMutation final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:baikaldb.pb.TableMutation) */ {
 public:
  inline TableMutation() : TableMutation(nullptr) {}
  ~TableMutation() override;
  explicit constexpr TableMutation(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TableMutation(const TableMutation& from);
  TableMutation(TableMutation&& from) noexcept
    : TableMutation() {
    *this = ::std::move(from);
  }

  inline TableMutation& operator=(const TableMutation& from) {
    CopyFrom(from);
    return *this;
  }
  inline TableMutation& operator=(TableMutation&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TableMutation& default_instance() {
    return *internal_default_instance();
  }
  static inline const TableMutation* internal_default_instance() {
    return reinterpret_cast<const TableMutation*>(
               &_TableMutation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(TableMutation& a, TableMutation& b) {
    a.Swap(&b);
  }
  inline void Swap(TableMutation* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TableMutation* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TableMutation* New() const final {
    return new TableMutation();
  }

  TableMutation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TableMutation>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TableMutation& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const TableMutation& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TableMutation* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "baikaldb.pb.TableMutation";
  }
  protected:
  explicit TableMutation(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInsertRowsFieldNumber = 2,
    kUpdateRowsFieldNumber = 3,
    kDeletedRowsFieldNumber = 4,
    kSequenceFieldNumber = 5,
    kSqlFieldNumber = 6,
    kTableIdFieldNumber = 1,
    kSignFieldNumber = 7,
  };
  // repeated bytes insert_rows = 2;
  int insert_rows_size() const;
  private:
  int _internal_insert_rows_size() const;
  public:
  void clear_insert_rows();
  const std::string& insert_rows(int index) const;
  std::string* mutable_insert_rows(int index);
  void set_insert_rows(int index, const std::string& value);
  void set_insert_rows(int index, std::string&& value);
  void set_insert_rows(int index, const char* value);
  void set_insert_rows(int index, const void* value, size_t size);
  std::string* add_insert_rows();
  void add_insert_rows(const std::string& value);
  void add_insert_rows(std::string&& value);
  void add_insert_rows(const char* value);
  void add_insert_rows(const void* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& insert_rows() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_insert_rows();
  private:
  const std::string& _internal_insert_rows(int index) const;
  std::string* _internal_add_insert_rows();
  public:

  // repeated bytes update_rows = 3;
  int update_rows_size() const;
  private:
  int _internal_update_rows_size() const;
  public:
  void clear_update_rows();
  const std::string& update_rows(int index) const;
  std::string* mutable_update_rows(int index);
  void set_update_rows(int index, const std::string& value);
  void set_update_rows(int index, std::string&& value);
  void set_update_rows(int index, const char* value);
  void set_update_rows(int index, const void* value, size_t size);
  std::string* add_update_rows();
  void add_update_rows(const std::string& value);
  void add_update_rows(std::string&& value);
  void add_update_rows(const char* value);
  void add_update_rows(const void* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& update_rows() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_update_rows();
  private:
  const std::string& _internal_update_rows(int index) const;
  std::string* _internal_add_update_rows();
  public:

  // repeated bytes deleted_rows = 4;
  int deleted_rows_size() const;
  private:
  int _internal_deleted_rows_size() const;
  public:
  void clear_deleted_rows();
  const std::string& deleted_rows(int index) const;
  std::string* mutable_deleted_rows(int index);
  void set_deleted_rows(int index, const std::string& value);
  void set_deleted_rows(int index, std::string&& value);
  void set_deleted_rows(int index, const char* value);
  void set_deleted_rows(int index, const void* value, size_t size);
  std::string* add_deleted_rows();
  void add_deleted_rows(const std::string& value);
  void add_deleted_rows(std::string&& value);
  void add_deleted_rows(const char* value);
  void add_deleted_rows(const void* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& deleted_rows() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_deleted_rows();
  private:
  const std::string& _internal_deleted_rows(int index) const;
  std::string* _internal_add_deleted_rows();
  public:

  // repeated .baikaldb.pb.MutationType sequence = 5;
  int sequence_size() const;
  private:
  int _internal_sequence_size() const;
  public:
  void clear_sequence();
  private:
  ::baikaldb::pb::MutationType _internal_sequence(int index) const;
  void _internal_add_sequence(::baikaldb::pb::MutationType value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>* _internal_mutable_sequence();
  public:
  ::baikaldb::pb::MutationType sequence(int index) const;
  void set_sequence(int index, ::baikaldb::pb::MutationType value);
  void add_sequence(::baikaldb::pb::MutationType value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>& sequence() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>* mutable_sequence();

  // optional bytes sql = 6;
  bool has_sql() const;
  private:
  bool _internal_has_sql() const;
  public:
  void clear_sql();
  const std::string& sql() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sql(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sql();
  PROTOBUF_MUST_USE_RESULT std::string* release_sql();
  void set_allocated_sql(std::string* sql);
  private:
  const std::string& _internal_sql() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sql(const std::string& value);
  std::string* _internal_mutable_sql();
  public:

  // optional int64 table_id = 1;
  bool has_table_id() const;
  private:
  bool _internal_has_table_id() const;
  public:
  void clear_table_id();
  ::PROTOBUF_NAMESPACE_ID::int64 table_id() const;
  void set_table_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_table_id() const;
  void _internal_set_table_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // optional uint64 sign = 7;
  bool has_sign() const;
  private:
  bool _internal_has_sign() const;
  public:
  void clear_sign();
  ::PROTOBUF_NAMESPACE_ID::uint64 sign() const;
  void set_sign(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_sign() const;
  void _internal_set_sign(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:baikaldb.pb.TableMutation)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> insert_rows_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> update_rows_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> deleted_rows_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int> sequence_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sql_;
  ::PROTOBUF_NAMESPACE_ID::int64 table_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 sign_;
  friend struct ::TableStruct_binlog_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Binlog

// optional .baikaldb.pb.BinlogType type = 1;
inline bool Binlog::_internal_has_type() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool Binlog::has_type() const {
  return _internal_has_type();
}
inline void Binlog::clear_type() {
  type_ = 0;
  _has_bits_[0] &= ~0x00000080u;
}
inline ::baikaldb::pb::BinlogType Binlog::_internal_type() const {
  return static_cast< ::baikaldb::pb::BinlogType >(type_);
}
inline ::baikaldb::pb::BinlogType Binlog::type() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.Binlog.type)
  return _internal_type();
}
inline void Binlog::_internal_set_type(::baikaldb::pb::BinlogType value) {
  assert(::baikaldb::pb::BinlogType_IsValid(value));
  _has_bits_[0] |= 0x00000080u;
  type_ = value;
}
inline void Binlog::set_type(::baikaldb::pb::BinlogType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.Binlog.type)
}

// optional int64 start_ts = 2;
inline bool Binlog::_internal_has_start_ts() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool Binlog::has_start_ts() const {
  return _internal_has_start_ts();
}
inline void Binlog::clear_start_ts() {
  start_ts_ = int64_t{0};
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Binlog::_internal_start_ts() const {
  return start_ts_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Binlog::start_ts() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.Binlog.start_ts)
  return _internal_start_ts();
}
inline void Binlog::_internal_set_start_ts(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000010u;
  start_ts_ = value;
}
inline void Binlog::set_start_ts(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_start_ts(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.Binlog.start_ts)
}

// optional int64 commit_ts = 3;
inline bool Binlog::_internal_has_commit_ts() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool Binlog::has_commit_ts() const {
  return _internal_has_commit_ts();
}
inline void Binlog::clear_commit_ts() {
  commit_ts_ = int64_t{0};
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Binlog::_internal_commit_ts() const {
  return commit_ts_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Binlog::commit_ts() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.Binlog.commit_ts)
  return _internal_commit_ts();
}
inline void Binlog::_internal_set_commit_ts(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000020u;
  commit_ts_ = value;
}
inline void Binlog::set_commit_ts(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_commit_ts(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.Binlog.commit_ts)
}

// optional bytes prewrite_key = 4;
inline bool Binlog::_internal_has_prewrite_key() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Binlog::has_prewrite_key() const {
  return _internal_has_prewrite_key();
}
inline void Binlog::clear_prewrite_key() {
  prewrite_key_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Binlog::prewrite_key() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.Binlog.prewrite_key)
  return _internal_prewrite_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Binlog::set_prewrite_key(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 prewrite_key_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:baikaldb.pb.Binlog.prewrite_key)
}
inline std::string* Binlog::mutable_prewrite_key() {
  std::string* _s = _internal_mutable_prewrite_key();
  // @@protoc_insertion_point(field_mutable:baikaldb.pb.Binlog.prewrite_key)
  return _s;
}
inline const std::string& Binlog::_internal_prewrite_key() const {
  return prewrite_key_.Get();
}
inline void Binlog::_internal_set_prewrite_key(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  prewrite_key_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Binlog::_internal_mutable_prewrite_key() {
  _has_bits_[0] |= 0x00000001u;
  return prewrite_key_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Binlog::release_prewrite_key() {
  // @@protoc_insertion_point(field_release:baikaldb.pb.Binlog.prewrite_key)
  if (!_internal_has_prewrite_key()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return prewrite_key_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Binlog::set_allocated_prewrite_key(std::string* prewrite_key) {
  if (prewrite_key != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  prewrite_key_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), prewrite_key,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:baikaldb.pb.Binlog.prewrite_key)
}

// optional .baikaldb.pb.PrewriteValue prewrite_value = 5;
inline bool Binlog::_internal_has_prewrite_value() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || prewrite_value_ != nullptr);
  return value;
}
inline bool Binlog::has_prewrite_value() const {
  return _internal_has_prewrite_value();
}
inline void Binlog::clear_prewrite_value() {
  if (prewrite_value_ != nullptr) prewrite_value_->Clear();
  _has_bits_[0] &= ~0x00000008u;
}
inline const ::baikaldb::pb::PrewriteValue& Binlog::_internal_prewrite_value() const {
  const ::baikaldb::pb::PrewriteValue* p = prewrite_value_;
  return p != nullptr ? *p : reinterpret_cast<const ::baikaldb::pb::PrewriteValue&>(
      ::baikaldb::pb::_PrewriteValue_default_instance_);
}
inline const ::baikaldb::pb::PrewriteValue& Binlog::prewrite_value() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.Binlog.prewrite_value)
  return _internal_prewrite_value();
}
inline void Binlog::unsafe_arena_set_allocated_prewrite_value(
    ::baikaldb::pb::PrewriteValue* prewrite_value) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(prewrite_value_);
  }
  prewrite_value_ = prewrite_value;
  if (prewrite_value) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:baikaldb.pb.Binlog.prewrite_value)
}
inline ::baikaldb::pb::PrewriteValue* Binlog::release_prewrite_value() {
  _has_bits_[0] &= ~0x00000008u;
  ::baikaldb::pb::PrewriteValue* temp = prewrite_value_;
  prewrite_value_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::baikaldb::pb::PrewriteValue* Binlog::unsafe_arena_release_prewrite_value() {
  // @@protoc_insertion_point(field_release:baikaldb.pb.Binlog.prewrite_value)
  _has_bits_[0] &= ~0x00000008u;
  ::baikaldb::pb::PrewriteValue* temp = prewrite_value_;
  prewrite_value_ = nullptr;
  return temp;
}
inline ::baikaldb::pb::PrewriteValue* Binlog::_internal_mutable_prewrite_value() {
  _has_bits_[0] |= 0x00000008u;
  if (prewrite_value_ == nullptr) {
    auto* p = CreateMaybeMessage<::baikaldb::pb::PrewriteValue>(GetArenaForAllocation());
    prewrite_value_ = p;
  }
  return prewrite_value_;
}
inline ::baikaldb::pb::PrewriteValue* Binlog::mutable_prewrite_value() {
  ::baikaldb::pb::PrewriteValue* _msg = _internal_mutable_prewrite_value();
  // @@protoc_insertion_point(field_mutable:baikaldb.pb.Binlog.prewrite_value)
  return _msg;
}
inline void Binlog::set_allocated_prewrite_value(::baikaldb::pb::PrewriteValue* prewrite_value) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete prewrite_value_;
  }
  if (prewrite_value) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::baikaldb::pb::PrewriteValue>::GetOwningArena(prewrite_value);
    if (message_arena != submessage_arena) {
      prewrite_value = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, prewrite_value, submessage_arena);
    }
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  prewrite_value_ = prewrite_value;
  // @@protoc_insertion_point(field_set_allocated:baikaldb.pb.Binlog.prewrite_value)
}

// optional bytes ddl_query = 6;
inline bool Binlog::_internal_has_ddl_query() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Binlog::has_ddl_query() const {
  return _internal_has_ddl_query();
}
inline void Binlog::clear_ddl_query() {
  ddl_query_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Binlog::ddl_query() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.Binlog.ddl_query)
  return _internal_ddl_query();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Binlog::set_ddl_query(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000002u;
 ddl_query_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:baikaldb.pb.Binlog.ddl_query)
}
inline std::string* Binlog::mutable_ddl_query() {
  std::string* _s = _internal_mutable_ddl_query();
  // @@protoc_insertion_point(field_mutable:baikaldb.pb.Binlog.ddl_query)
  return _s;
}
inline const std::string& Binlog::_internal_ddl_query() const {
  return ddl_query_.Get();
}
inline void Binlog::_internal_set_ddl_query(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  ddl_query_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Binlog::_internal_mutable_ddl_query() {
  _has_bits_[0] |= 0x00000002u;
  return ddl_query_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Binlog::release_ddl_query() {
  // @@protoc_insertion_point(field_release:baikaldb.pb.Binlog.ddl_query)
  if (!_internal_has_ddl_query()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return ddl_query_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Binlog::set_allocated_ddl_query(std::string* ddl_query) {
  if (ddl_query != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  ddl_query_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ddl_query,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:baikaldb.pb.Binlog.ddl_query)
}

// optional bytes stmts = 7;
inline bool Binlog::_internal_has_stmts() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Binlog::has_stmts() const {
  return _internal_has_stmts();
}
inline void Binlog::clear_stmts() {
  stmts_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& Binlog::stmts() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.Binlog.stmts)
  return _internal_stmts();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Binlog::set_stmts(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000004u;
 stmts_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:baikaldb.pb.Binlog.stmts)
}
inline std::string* Binlog::mutable_stmts() {
  std::string* _s = _internal_mutable_stmts();
  // @@protoc_insertion_point(field_mutable:baikaldb.pb.Binlog.stmts)
  return _s;
}
inline const std::string& Binlog::_internal_stmts() const {
  return stmts_.Get();
}
inline void Binlog::_internal_set_stmts(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  stmts_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Binlog::_internal_mutable_stmts() {
  _has_bits_[0] |= 0x00000004u;
  return stmts_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Binlog::release_stmts() {
  // @@protoc_insertion_point(field_release:baikaldb.pb.Binlog.stmts)
  if (!_internal_has_stmts()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return stmts_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Binlog::set_allocated_stmts(std::string* stmts) {
  if (stmts != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  stmts_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), stmts,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:baikaldb.pb.Binlog.stmts)
}

// optional uint64 partition_key = 8;
inline bool Binlog::_internal_has_partition_key() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool Binlog::has_partition_key() const {
  return _internal_has_partition_key();
}
inline void Binlog::clear_partition_key() {
  partition_key_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000040u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Binlog::_internal_partition_key() const {
  return partition_key_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Binlog::partition_key() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.Binlog.partition_key)
  return _internal_partition_key();
}
inline void Binlog::_internal_set_partition_key(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000040u;
  partition_key_ = value;
}
inline void Binlog::set_partition_key(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_partition_key(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.Binlog.partition_key)
}

// -------------------------------------------------------------------

// PrewriteValue

// optional int64 schema_version = 1;
inline bool PrewriteValue::_internal_has_schema_version() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool PrewriteValue::has_schema_version() const {
  return _internal_has_schema_version();
}
inline void PrewriteValue::clear_schema_version() {
  schema_version_ = int64_t{0};
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 PrewriteValue::_internal_schema_version() const {
  return schema_version_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 PrewriteValue::schema_version() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.PrewriteValue.schema_version)
  return _internal_schema_version();
}
inline void PrewriteValue::_internal_set_schema_version(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  schema_version_ = value;
}
inline void PrewriteValue::set_schema_version(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_schema_version(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.PrewriteValue.schema_version)
}

// repeated .baikaldb.pb.TableMutation mutations = 2;
inline int PrewriteValue::_internal_mutations_size() const {
  return mutations_.size();
}
inline int PrewriteValue::mutations_size() const {
  return _internal_mutations_size();
}
inline void PrewriteValue::clear_mutations() {
  mutations_.Clear();
}
inline ::baikaldb::pb::TableMutation* PrewriteValue::mutable_mutations(int index) {
  // @@protoc_insertion_point(field_mutable:baikaldb.pb.PrewriteValue.mutations)
  return mutations_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::baikaldb::pb::TableMutation >*
PrewriteValue::mutable_mutations() {
  // @@protoc_insertion_point(field_mutable_list:baikaldb.pb.PrewriteValue.mutations)
  return &mutations_;
}
inline const ::baikaldb::pb::TableMutation& PrewriteValue::_internal_mutations(int index) const {
  return mutations_.Get(index);
}
inline const ::baikaldb::pb::TableMutation& PrewriteValue::mutations(int index) const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.PrewriteValue.mutations)
  return _internal_mutations(index);
}
inline ::baikaldb::pb::TableMutation* PrewriteValue::_internal_add_mutations() {
  return mutations_.Add();
}
inline ::baikaldb::pb::TableMutation* PrewriteValue::add_mutations() {
  ::baikaldb::pb::TableMutation* _add = _internal_add_mutations();
  // @@protoc_insertion_point(field_add:baikaldb.pb.PrewriteValue.mutations)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::baikaldb::pb::TableMutation >&
PrewriteValue::mutations() const {
  // @@protoc_insertion_point(field_list:baikaldb.pb.PrewriteValue.mutations)
  return mutations_;
}

// -------------------------------------------------------------------

// TableMutation

// optional int64 table_id = 1;
inline bool TableMutation::_internal_has_table_id() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool TableMutation::has_table_id() const {
  return _internal_has_table_id();
}
inline void TableMutation::clear_table_id() {
  table_id_ = int64_t{0};
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TableMutation::_internal_table_id() const {
  return table_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TableMutation::table_id() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.TableMutation.table_id)
  return _internal_table_id();
}
inline void TableMutation::_internal_set_table_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000002u;
  table_id_ = value;
}
inline void TableMutation::set_table_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_table_id(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.TableMutation.table_id)
}

// repeated bytes insert_rows = 2;
inline int TableMutation::_internal_insert_rows_size() const {
  return insert_rows_.size();
}
inline int TableMutation::insert_rows_size() const {
  return _internal_insert_rows_size();
}
inline void TableMutation::clear_insert_rows() {
  insert_rows_.Clear();
}
inline std::string* TableMutation::add_insert_rows() {
  std::string* _s = _internal_add_insert_rows();
  // @@protoc_insertion_point(field_add_mutable:baikaldb.pb.TableMutation.insert_rows)
  return _s;
}
inline const std::string& TableMutation::_internal_insert_rows(int index) const {
  return insert_rows_.Get(index);
}
inline const std::string& TableMutation::insert_rows(int index) const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.TableMutation.insert_rows)
  return _internal_insert_rows(index);
}
inline std::string* TableMutation::mutable_insert_rows(int index) {
  // @@protoc_insertion_point(field_mutable:baikaldb.pb.TableMutation.insert_rows)
  return insert_rows_.Mutable(index);
}
inline void TableMutation::set_insert_rows(int index, const std::string& value) {
  insert_rows_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.TableMutation.insert_rows)
}
inline void TableMutation::set_insert_rows(int index, std::string&& value) {
  insert_rows_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:baikaldb.pb.TableMutation.insert_rows)
}
inline void TableMutation::set_insert_rows(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  insert_rows_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:baikaldb.pb.TableMutation.insert_rows)
}
inline void TableMutation::set_insert_rows(int index, const void* value, size_t size) {
  insert_rows_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:baikaldb.pb.TableMutation.insert_rows)
}
inline std::string* TableMutation::_internal_add_insert_rows() {
  return insert_rows_.Add();
}
inline void TableMutation::add_insert_rows(const std::string& value) {
  insert_rows_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:baikaldb.pb.TableMutation.insert_rows)
}
inline void TableMutation::add_insert_rows(std::string&& value) {
  insert_rows_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:baikaldb.pb.TableMutation.insert_rows)
}
inline void TableMutation::add_insert_rows(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  insert_rows_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:baikaldb.pb.TableMutation.insert_rows)
}
inline void TableMutation::add_insert_rows(const void* value, size_t size) {
  insert_rows_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:baikaldb.pb.TableMutation.insert_rows)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
TableMutation::insert_rows() const {
  // @@protoc_insertion_point(field_list:baikaldb.pb.TableMutation.insert_rows)
  return insert_rows_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
TableMutation::mutable_insert_rows() {
  // @@protoc_insertion_point(field_mutable_list:baikaldb.pb.TableMutation.insert_rows)
  return &insert_rows_;
}

// repeated bytes update_rows = 3;
inline int TableMutation::_internal_update_rows_size() const {
  return update_rows_.size();
}
inline int TableMutation::update_rows_size() const {
  return _internal_update_rows_size();
}
inline void TableMutation::clear_update_rows() {
  update_rows_.Clear();
}
inline std::string* TableMutation::add_update_rows() {
  std::string* _s = _internal_add_update_rows();
  // @@protoc_insertion_point(field_add_mutable:baikaldb.pb.TableMutation.update_rows)
  return _s;
}
inline const std::string& TableMutation::_internal_update_rows(int index) const {
  return update_rows_.Get(index);
}
inline const std::string& TableMutation::update_rows(int index) const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.TableMutation.update_rows)
  return _internal_update_rows(index);
}
inline std::string* TableMutation::mutable_update_rows(int index) {
  // @@protoc_insertion_point(field_mutable:baikaldb.pb.TableMutation.update_rows)
  return update_rows_.Mutable(index);
}
inline void TableMutation::set_update_rows(int index, const std::string& value) {
  update_rows_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.TableMutation.update_rows)
}
inline void TableMutation::set_update_rows(int index, std::string&& value) {
  update_rows_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:baikaldb.pb.TableMutation.update_rows)
}
inline void TableMutation::set_update_rows(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  update_rows_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:baikaldb.pb.TableMutation.update_rows)
}
inline void TableMutation::set_update_rows(int index, const void* value, size_t size) {
  update_rows_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:baikaldb.pb.TableMutation.update_rows)
}
inline std::string* TableMutation::_internal_add_update_rows() {
  return update_rows_.Add();
}
inline void TableMutation::add_update_rows(const std::string& value) {
  update_rows_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:baikaldb.pb.TableMutation.update_rows)
}
inline void TableMutation::add_update_rows(std::string&& value) {
  update_rows_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:baikaldb.pb.TableMutation.update_rows)
}
inline void TableMutation::add_update_rows(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  update_rows_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:baikaldb.pb.TableMutation.update_rows)
}
inline void TableMutation::add_update_rows(const void* value, size_t size) {
  update_rows_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:baikaldb.pb.TableMutation.update_rows)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
TableMutation::update_rows() const {
  // @@protoc_insertion_point(field_list:baikaldb.pb.TableMutation.update_rows)
  return update_rows_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
TableMutation::mutable_update_rows() {
  // @@protoc_insertion_point(field_mutable_list:baikaldb.pb.TableMutation.update_rows)
  return &update_rows_;
}

// repeated bytes deleted_rows = 4;
inline int TableMutation::_internal_deleted_rows_size() const {
  return deleted_rows_.size();
}
inline int TableMutation::deleted_rows_size() const {
  return _internal_deleted_rows_size();
}
inline void TableMutation::clear_deleted_rows() {
  deleted_rows_.Clear();
}
inline std::string* TableMutation::add_deleted_rows() {
  std::string* _s = _internal_add_deleted_rows();
  // @@protoc_insertion_point(field_add_mutable:baikaldb.pb.TableMutation.deleted_rows)
  return _s;
}
inline const std::string& TableMutation::_internal_deleted_rows(int index) const {
  return deleted_rows_.Get(index);
}
inline const std::string& TableMutation::deleted_rows(int index) const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.TableMutation.deleted_rows)
  return _internal_deleted_rows(index);
}
inline std::string* TableMutation::mutable_deleted_rows(int index) {
  // @@protoc_insertion_point(field_mutable:baikaldb.pb.TableMutation.deleted_rows)
  return deleted_rows_.Mutable(index);
}
inline void TableMutation::set_deleted_rows(int index, const std::string& value) {
  deleted_rows_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.TableMutation.deleted_rows)
}
inline void TableMutation::set_deleted_rows(int index, std::string&& value) {
  deleted_rows_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:baikaldb.pb.TableMutation.deleted_rows)
}
inline void TableMutation::set_deleted_rows(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  deleted_rows_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:baikaldb.pb.TableMutation.deleted_rows)
}
inline void TableMutation::set_deleted_rows(int index, const void* value, size_t size) {
  deleted_rows_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:baikaldb.pb.TableMutation.deleted_rows)
}
inline std::string* TableMutation::_internal_add_deleted_rows() {
  return deleted_rows_.Add();
}
inline void TableMutation::add_deleted_rows(const std::string& value) {
  deleted_rows_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:baikaldb.pb.TableMutation.deleted_rows)
}
inline void TableMutation::add_deleted_rows(std::string&& value) {
  deleted_rows_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:baikaldb.pb.TableMutation.deleted_rows)
}
inline void TableMutation::add_deleted_rows(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  deleted_rows_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:baikaldb.pb.TableMutation.deleted_rows)
}
inline void TableMutation::add_deleted_rows(const void* value, size_t size) {
  deleted_rows_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:baikaldb.pb.TableMutation.deleted_rows)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
TableMutation::deleted_rows() const {
  // @@protoc_insertion_point(field_list:baikaldb.pb.TableMutation.deleted_rows)
  return deleted_rows_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
TableMutation::mutable_deleted_rows() {
  // @@protoc_insertion_point(field_mutable_list:baikaldb.pb.TableMutation.deleted_rows)
  return &deleted_rows_;
}

// repeated .baikaldb.pb.MutationType sequence = 5;
inline int TableMutation::_internal_sequence_size() const {
  return sequence_.size();
}
inline int TableMutation::sequence_size() const {
  return _internal_sequence_size();
}
inline void TableMutation::clear_sequence() {
  sequence_.Clear();
}
inline ::baikaldb::pb::MutationType TableMutation::_internal_sequence(int index) const {
  return static_cast< ::baikaldb::pb::MutationType >(sequence_.Get(index));
}
inline ::baikaldb::pb::MutationType TableMutation::sequence(int index) const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.TableMutation.sequence)
  return _internal_sequence(index);
}
inline void TableMutation::set_sequence(int index, ::baikaldb::pb::MutationType value) {
  assert(::baikaldb::pb::MutationType_IsValid(value));
  sequence_.Set(index, value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.TableMutation.sequence)
}
inline void TableMutation::_internal_add_sequence(::baikaldb::pb::MutationType value) {
  assert(::baikaldb::pb::MutationType_IsValid(value));
  sequence_.Add(value);
}
inline void TableMutation::add_sequence(::baikaldb::pb::MutationType value) {
  _internal_add_sequence(value);
  // @@protoc_insertion_point(field_add:baikaldb.pb.TableMutation.sequence)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>&
TableMutation::sequence() const {
  // @@protoc_insertion_point(field_list:baikaldb.pb.TableMutation.sequence)
  return sequence_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>*
TableMutation::_internal_mutable_sequence() {
  return &sequence_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>*
TableMutation::mutable_sequence() {
  // @@protoc_insertion_point(field_mutable_list:baikaldb.pb.TableMutation.sequence)
  return _internal_mutable_sequence();
}

// optional bytes sql = 6;
inline bool TableMutation::_internal_has_sql() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool TableMutation::has_sql() const {
  return _internal_has_sql();
}
inline void TableMutation::clear_sql() {
  sql_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& TableMutation::sql() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.TableMutation.sql)
  return _internal_sql();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TableMutation::set_sql(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 sql_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:baikaldb.pb.TableMutation.sql)
}
inline std::string* TableMutation::mutable_sql() {
  std::string* _s = _internal_mutable_sql();
  // @@protoc_insertion_point(field_mutable:baikaldb.pb.TableMutation.sql)
  return _s;
}
inline const std::string& TableMutation::_internal_sql() const {
  return sql_.Get();
}
inline void TableMutation::_internal_set_sql(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  sql_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* TableMutation::_internal_mutable_sql() {
  _has_bits_[0] |= 0x00000001u;
  return sql_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* TableMutation::release_sql() {
  // @@protoc_insertion_point(field_release:baikaldb.pb.TableMutation.sql)
  if (!_internal_has_sql()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return sql_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void TableMutation::set_allocated_sql(std::string* sql) {
  if (sql != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  sql_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sql,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:baikaldb.pb.TableMutation.sql)
}

// optional uint64 sign = 7;
inline bool TableMutation::_internal_has_sign() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool TableMutation::has_sign() const {
  return _internal_has_sign();
}
inline void TableMutation::clear_sign() {
  sign_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 TableMutation::_internal_sign() const {
  return sign_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 TableMutation::sign() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.TableMutation.sign)
  return _internal_sign();
}
inline void TableMutation::_internal_set_sign(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000004u;
  sign_ = value;
}
inline void TableMutation::set_sign(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_sign(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.TableMutation.sign)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace baikaldb

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::baikaldb::pb::BinlogType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::baikaldb::pb::BinlogType>() {
  return ::baikaldb::pb::BinlogType_descriptor();
}
template <> struct is_proto_enum< ::baikaldb::pb::MutationType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::baikaldb::pb::MutationType>() {
  return ::baikaldb::pb::MutationType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_binlog_2eproto
