// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compaction.interface.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_compaction_2einterface_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_compaction_2einterface_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3018000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3018000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_compaction_2einterface_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_compaction_2einterface_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_compaction_2einterface_2eproto;
namespace baikaldb {
namespace pb {
class RemoteCompactionRequest;
struct RemoteCompactionRequestDefaultTypeInternal;
extern RemoteCompactionRequestDefaultTypeInternal _RemoteCompactionRequest_default_instance_;
class RemoteCompactionResponse;
struct RemoteCompactionResponseDefaultTypeInternal;
extern RemoteCompactionResponseDefaultTypeInternal _RemoteCompactionResponse_default_instance_;
class RocksdbGFLAGS;
struct RocksdbGFLAGSDefaultTypeInternal;
extern RocksdbGFLAGSDefaultTypeInternal _RocksdbGFLAGS_default_instance_;
}  // namespace pb
}  // namespace baikaldb
PROTOBUF_NAMESPACE_OPEN
template<> ::baikaldb::pb::RemoteCompactionRequest* Arena::CreateMaybeMessage<::baikaldb::pb::RemoteCompactionRequest>(Arena*);
template<> ::baikaldb::pb::RemoteCompactionResponse* Arena::CreateMaybeMessage<::baikaldb::pb::RemoteCompactionResponse>(Arena*);
template<> ::baikaldb::pb::RocksdbGFLAGS* Arena::CreateMaybeMessage<::baikaldb::pb::RocksdbGFLAGS>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace baikaldb {
namespace pb {

// ===================================================================

class RocksdbGFLAGS final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:baikaldb.pb.RocksdbGFLAGS) */ {
 public:
  inline RocksdbGFLAGS() : RocksdbGFLAGS(nullptr) {}
  ~RocksdbGFLAGS() override;
  explicit constexpr RocksdbGFLAGS(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RocksdbGFLAGS(const RocksdbGFLAGS& from);
  RocksdbGFLAGS(RocksdbGFLAGS&& from) noexcept
    : RocksdbGFLAGS() {
    *this = ::std::move(from);
  }

  inline RocksdbGFLAGS& operator=(const RocksdbGFLAGS& from) {
    CopyFrom(from);
    return *this;
  }
  inline RocksdbGFLAGS& operator=(RocksdbGFLAGS&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RocksdbGFLAGS& default_instance() {
    return *internal_default_instance();
  }
  static inline const RocksdbGFLAGS* internal_default_instance() {
    return reinterpret_cast<const RocksdbGFLAGS*>(
               &_RocksdbGFLAGS_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RocksdbGFLAGS& a, RocksdbGFLAGS& b) {
    a.Swap(&b);
  }
  inline void Swap(RocksdbGFLAGS* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RocksdbGFLAGS* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RocksdbGFLAGS* New() const final {
    return new RocksdbGFLAGS();
  }

  RocksdbGFLAGS* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RocksdbGFLAGS>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RocksdbGFLAGS& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const RocksdbGFLAGS& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RocksdbGFLAGS* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "baikaldb.pb.RocksdbGFLAGS";
  }
  protected:
  explicit RocksdbGFLAGS(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRocksUsePartitionedIndexFiltersFieldNumber = 1,
    kRocksUseRibbonFilterFieldNumber = 2,
    kOlapTableOnlyFieldNumber = 3,
    kOlapImportModeFieldNumber = 4,
    kKeyPointCollectorIntervalFieldNumber = 6,
    kRocksBlockCacheSizeMbFieldNumber = 7,
    kRocksHighPriPoolRatioFieldNumber = 8,
    kRocksUseSstPartitionerFixedPrefixFieldNumber = 5,
    kRocksUseHyperClockCacheFieldNumber = 9,
    kRocksBlockSizeFieldNumber = 10,
  };
  // optional bool rocks_use_partitioned_index_filters = 1;
  bool has_rocks_use_partitioned_index_filters() const;
  private:
  bool _internal_has_rocks_use_partitioned_index_filters() const;
  public:
  void clear_rocks_use_partitioned_index_filters();
  bool rocks_use_partitioned_index_filters() const;
  void set_rocks_use_partitioned_index_filters(bool value);
  private:
  bool _internal_rocks_use_partitioned_index_filters() const;
  void _internal_set_rocks_use_partitioned_index_filters(bool value);
  public:

  // optional bool rocks_use_ribbon_filter = 2;
  bool has_rocks_use_ribbon_filter() const;
  private:
  bool _internal_has_rocks_use_ribbon_filter() const;
  public:
  void clear_rocks_use_ribbon_filter();
  bool rocks_use_ribbon_filter() const;
  void set_rocks_use_ribbon_filter(bool value);
  private:
  bool _internal_rocks_use_ribbon_filter() const;
  void _internal_set_rocks_use_ribbon_filter(bool value);
  public:

  // optional bool olap_table_only = 3;
  bool has_olap_table_only() const;
  private:
  bool _internal_has_olap_table_only() const;
  public:
  void clear_olap_table_only();
  bool olap_table_only() const;
  void set_olap_table_only(bool value);
  private:
  bool _internal_olap_table_only() const;
  void _internal_set_olap_table_only(bool value);
  public:

  // optional bool olap_import_mode = 4;
  bool has_olap_import_mode() const;
  private:
  bool _internal_has_olap_import_mode() const;
  public:
  void clear_olap_import_mode();
  bool olap_import_mode() const;
  void set_olap_import_mode(bool value);
  private:
  bool _internal_olap_import_mode() const;
  void _internal_set_olap_import_mode(bool value);
  public:

  // optional int32 key_point_collector_interval = 6;
  bool has_key_point_collector_interval() const;
  private:
  bool _internal_has_key_point_collector_interval() const;
  public:
  void clear_key_point_collector_interval();
  ::PROTOBUF_NAMESPACE_ID::int32 key_point_collector_interval() const;
  void set_key_point_collector_interval(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_key_point_collector_interval() const;
  void _internal_set_key_point_collector_interval(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional int64 rocks_block_cache_size_mb = 7;
  bool has_rocks_block_cache_size_mb() const;
  private:
  bool _internal_has_rocks_block_cache_size_mb() const;
  public:
  void clear_rocks_block_cache_size_mb();
  ::PROTOBUF_NAMESPACE_ID::int64 rocks_block_cache_size_mb() const;
  void set_rocks_block_cache_size_mb(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_rocks_block_cache_size_mb() const;
  void _internal_set_rocks_block_cache_size_mb(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // optional double rocks_high_pri_pool_ratio = 8;
  bool has_rocks_high_pri_pool_ratio() const;
  private:
  bool _internal_has_rocks_high_pri_pool_ratio() const;
  public:
  void clear_rocks_high_pri_pool_ratio();
  double rocks_high_pri_pool_ratio() const;
  void set_rocks_high_pri_pool_ratio(double value);
  private:
  double _internal_rocks_high_pri_pool_ratio() const;
  void _internal_set_rocks_high_pri_pool_ratio(double value);
  public:

  // optional bool rocks_use_sst_partitioner_fixed_prefix = 5;
  bool has_rocks_use_sst_partitioner_fixed_prefix() const;
  private:
  bool _internal_has_rocks_use_sst_partitioner_fixed_prefix() const;
  public:
  void clear_rocks_use_sst_partitioner_fixed_prefix();
  bool rocks_use_sst_partitioner_fixed_prefix() const;
  void set_rocks_use_sst_partitioner_fixed_prefix(bool value);
  private:
  bool _internal_rocks_use_sst_partitioner_fixed_prefix() const;
  void _internal_set_rocks_use_sst_partitioner_fixed_prefix(bool value);
  public:

  // optional bool rocks_use_hyper_clock_cache = 9;
  bool has_rocks_use_hyper_clock_cache() const;
  private:
  bool _internal_has_rocks_use_hyper_clock_cache() const;
  public:
  void clear_rocks_use_hyper_clock_cache();
  bool rocks_use_hyper_clock_cache() const;
  void set_rocks_use_hyper_clock_cache(bool value);
  private:
  bool _internal_rocks_use_hyper_clock_cache() const;
  void _internal_set_rocks_use_hyper_clock_cache(bool value);
  public:

  // optional int32 rocks_block_size = 10;
  bool has_rocks_block_size() const;
  private:
  bool _internal_has_rocks_block_size() const;
  public:
  void clear_rocks_block_size();
  ::PROTOBUF_NAMESPACE_ID::int32 rocks_block_size() const;
  void set_rocks_block_size(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_rocks_block_size() const;
  void _internal_set_rocks_block_size(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:baikaldb.pb.RocksdbGFLAGS)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  bool rocks_use_partitioned_index_filters_;
  bool rocks_use_ribbon_filter_;
  bool olap_table_only_;
  bool olap_import_mode_;
  ::PROTOBUF_NAMESPACE_ID::int32 key_point_collector_interval_;
  ::PROTOBUF_NAMESPACE_ID::int64 rocks_block_cache_size_mb_;
  double rocks_high_pri_pool_ratio_;
  bool rocks_use_sst_partitioner_fixed_prefix_;
  bool rocks_use_hyper_clock_cache_;
  ::PROTOBUF_NAMESPACE_ID::int32 rocks_block_size_;
  friend struct ::TableStruct_compaction_2einterface_2eproto;
};
// -------------------------------------------------------------------

class RemoteCompactionRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:baikaldb.pb.RemoteCompactionRequest) */ {
 public:
  inline RemoteCompactionRequest() : RemoteCompactionRequest(nullptr) {}
  ~RemoteCompactionRequest() override;
  explicit constexpr RemoteCompactionRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RemoteCompactionRequest(const RemoteCompactionRequest& from);
  RemoteCompactionRequest(RemoteCompactionRequest&& from) noexcept
    : RemoteCompactionRequest() {
    *this = ::std::move(from);
  }

  inline RemoteCompactionRequest& operator=(const RemoteCompactionRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline RemoteCompactionRequest& operator=(RemoteCompactionRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RemoteCompactionRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const RemoteCompactionRequest* internal_default_instance() {
    return reinterpret_cast<const RemoteCompactionRequest*>(
               &_RemoteCompactionRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RemoteCompactionRequest& a, RemoteCompactionRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(RemoteCompactionRequest* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RemoteCompactionRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RemoteCompactionRequest* New() const final {
    return new RemoteCompactionRequest();
  }

  RemoteCompactionRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RemoteCompactionRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RemoteCompactionRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const RemoteCompactionRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RemoteCompactionRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "baikaldb.pb.RemoteCompactionRequest";
  }
  protected:
  explicit RemoteCompactionRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRemoteCompactionIdFieldNumber = 1,
    kCompactionInputBinaryFieldNumber = 2,
    kAddressFieldNumber = 3,
    kCfNameFieldNumber = 4,
    kRocksdbGflagsFieldNumber = 5,
  };
  // optional string remote_compaction_id = 1;
  bool has_remote_compaction_id() const;
  private:
  bool _internal_has_remote_compaction_id() const;
  public:
  void clear_remote_compaction_id();
  const std::string& remote_compaction_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_remote_compaction_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_remote_compaction_id();
  PROTOBUF_MUST_USE_RESULT std::string* release_remote_compaction_id();
  void set_allocated_remote_compaction_id(std::string* remote_compaction_id);
  private:
  const std::string& _internal_remote_compaction_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_remote_compaction_id(const std::string& value);
  std::string* _internal_mutable_remote_compaction_id();
  public:

  // optional bytes compaction_input_binary = 2;
  bool has_compaction_input_binary() const;
  private:
  bool _internal_has_compaction_input_binary() const;
  public:
  void clear_compaction_input_binary();
  const std::string& compaction_input_binary() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_compaction_input_binary(ArgT0&& arg0, ArgT... args);
  std::string* mutable_compaction_input_binary();
  PROTOBUF_MUST_USE_RESULT std::string* release_compaction_input_binary();
  void set_allocated_compaction_input_binary(std::string* compaction_input_binary);
  private:
  const std::string& _internal_compaction_input_binary() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_compaction_input_binary(const std::string& value);
  std::string* _internal_mutable_compaction_input_binary();
  public:

  // optional string address = 3;
  bool has_address() const;
  private:
  bool _internal_has_address() const;
  public:
  void clear_address();
  const std::string& address() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_address(ArgT0&& arg0, ArgT... args);
  std::string* mutable_address();
  PROTOBUF_MUST_USE_RESULT std::string* release_address();
  void set_allocated_address(std::string* address);
  private:
  const std::string& _internal_address() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_address(const std::string& value);
  std::string* _internal_mutable_address();
  public:

  // optional string cf_name = 4;
  bool has_cf_name() const;
  private:
  bool _internal_has_cf_name() const;
  public:
  void clear_cf_name();
  const std::string& cf_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_cf_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_cf_name();
  PROTOBUF_MUST_USE_RESULT std::string* release_cf_name();
  void set_allocated_cf_name(std::string* cf_name);
  private:
  const std::string& _internal_cf_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_cf_name(const std::string& value);
  std::string* _internal_mutable_cf_name();
  public:

  // optional .baikaldb.pb.RocksdbGFLAGS rocksdb_gflags = 5;
  bool has_rocksdb_gflags() const;
  private:
  bool _internal_has_rocksdb_gflags() const;
  public:
  void clear_rocksdb_gflags();
  const ::baikaldb::pb::RocksdbGFLAGS& rocksdb_gflags() const;
  PROTOBUF_MUST_USE_RESULT ::baikaldb::pb::RocksdbGFLAGS* release_rocksdb_gflags();
  ::baikaldb::pb::RocksdbGFLAGS* mutable_rocksdb_gflags();
  void set_allocated_rocksdb_gflags(::baikaldb::pb::RocksdbGFLAGS* rocksdb_gflags);
  private:
  const ::baikaldb::pb::RocksdbGFLAGS& _internal_rocksdb_gflags() const;
  ::baikaldb::pb::RocksdbGFLAGS* _internal_mutable_rocksdb_gflags();
  public:
  void unsafe_arena_set_allocated_rocksdb_gflags(
      ::baikaldb::pb::RocksdbGFLAGS* rocksdb_gflags);
  ::baikaldb::pb::RocksdbGFLAGS* unsafe_arena_release_rocksdb_gflags();

  // @@protoc_insertion_point(class_scope:baikaldb.pb.RemoteCompactionRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr remote_compaction_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr compaction_input_binary_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr address_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr cf_name_;
  ::baikaldb::pb::RocksdbGFLAGS* rocksdb_gflags_;
  friend struct ::TableStruct_compaction_2einterface_2eproto;
};
// -------------------------------------------------------------------

class RemoteCompactionResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:baikaldb.pb.RemoteCompactionResponse) */ {
 public:
  inline RemoteCompactionResponse() : RemoteCompactionResponse(nullptr) {}
  ~RemoteCompactionResponse() override;
  explicit constexpr RemoteCompactionResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RemoteCompactionResponse(const RemoteCompactionResponse& from);
  RemoteCompactionResponse(RemoteCompactionResponse&& from) noexcept
    : RemoteCompactionResponse() {
    *this = ::std::move(from);
  }

  inline RemoteCompactionResponse& operator=(const RemoteCompactionResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline RemoteCompactionResponse& operator=(RemoteCompactionResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RemoteCompactionResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const RemoteCompactionResponse* internal_default_instance() {
    return reinterpret_cast<const RemoteCompactionResponse*>(
               &_RemoteCompactionResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(RemoteCompactionResponse& a, RemoteCompactionResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(RemoteCompactionResponse* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RemoteCompactionResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RemoteCompactionResponse* New() const final {
    return new RemoteCompactionResponse();
  }

  RemoteCompactionResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RemoteCompactionResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RemoteCompactionResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const RemoteCompactionResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RemoteCompactionResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "baikaldb.pb.RemoteCompactionResponse";
  }
  protected:
  explicit RemoteCompactionResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOutputFileInfoFieldNumber = 3,
    kCompactionResultBinaryFieldNumber = 2,
    kErrcodeFieldNumber = 1,
  };
  // repeated .baikaldb.pb.CompactionFileInfo output_file_info = 3;
  int output_file_info_size() const;
  private:
  int _internal_output_file_info_size() const;
  public:
  void clear_output_file_info();
  ::baikaldb::pb::CompactionFileInfo* mutable_output_file_info(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::baikaldb::pb::CompactionFileInfo >*
      mutable_output_file_info();
  private:
  const ::baikaldb::pb::CompactionFileInfo& _internal_output_file_info(int index) const;
  ::baikaldb::pb::CompactionFileInfo* _internal_add_output_file_info();
  public:
  const ::baikaldb::pb::CompactionFileInfo& output_file_info(int index) const;
  ::baikaldb::pb::CompactionFileInfo* add_output_file_info();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::baikaldb::pb::CompactionFileInfo >&
      output_file_info() const;

  // optional bytes compaction_result_binary = 2;
  bool has_compaction_result_binary() const;
  private:
  bool _internal_has_compaction_result_binary() const;
  public:
  void clear_compaction_result_binary();
  const std::string& compaction_result_binary() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_compaction_result_binary(ArgT0&& arg0, ArgT... args);
  std::string* mutable_compaction_result_binary();
  PROTOBUF_MUST_USE_RESULT std::string* release_compaction_result_binary();
  void set_allocated_compaction_result_binary(std::string* compaction_result_binary);
  private:
  const std::string& _internal_compaction_result_binary() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_compaction_result_binary(const std::string& value);
  std::string* _internal_mutable_compaction_result_binary();
  public:

  // optional .baikaldb.pb.ErrCode errcode = 1;
  bool has_errcode() const;
  private:
  bool _internal_has_errcode() const;
  public:
  void clear_errcode();
  ::baikaldb::pb::ErrCode errcode() const;
  void set_errcode(::baikaldb::pb::ErrCode value);
  private:
  ::baikaldb::pb::ErrCode _internal_errcode() const;
  void _internal_set_errcode(::baikaldb::pb::ErrCode value);
  public:

  // @@protoc_insertion_point(class_scope:baikaldb.pb.RemoteCompactionResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::baikaldb::pb::CompactionFileInfo > output_file_info_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr compaction_result_binary_;
  int errcode_;
  friend struct ::TableStruct_compaction_2einterface_2eproto;
};
// ===================================================================

class CompactionService_Stub;

class CompactionService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline CompactionService() {};
 public:
  virtual ~CompactionService();

  typedef CompactionService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void do_compaction(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::baikaldb::pb::RemoteCompactionRequest* request,
                       ::baikaldb::pb::RemoteCompactionResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(CompactionService);
};

class CompactionService_Stub : public CompactionService {
 public:
  CompactionService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  CompactionService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~CompactionService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements CompactionService ------------------------------------------

  void do_compaction(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::baikaldb::pb::RemoteCompactionRequest* request,
                       ::baikaldb::pb::RemoteCompactionResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(CompactionService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RocksdbGFLAGS

// optional bool rocks_use_partitioned_index_filters = 1;
inline bool RocksdbGFLAGS::_internal_has_rocks_use_partitioned_index_filters() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool RocksdbGFLAGS::has_rocks_use_partitioned_index_filters() const {
  return _internal_has_rocks_use_partitioned_index_filters();
}
inline void RocksdbGFLAGS::clear_rocks_use_partitioned_index_filters() {
  rocks_use_partitioned_index_filters_ = false;
  _has_bits_[0] &= ~0x00000001u;
}
inline bool RocksdbGFLAGS::_internal_rocks_use_partitioned_index_filters() const {
  return rocks_use_partitioned_index_filters_;
}
inline bool RocksdbGFLAGS::rocks_use_partitioned_index_filters() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.RocksdbGFLAGS.rocks_use_partitioned_index_filters)
  return _internal_rocks_use_partitioned_index_filters();
}
inline void RocksdbGFLAGS::_internal_set_rocks_use_partitioned_index_filters(bool value) {
  _has_bits_[0] |= 0x00000001u;
  rocks_use_partitioned_index_filters_ = value;
}
inline void RocksdbGFLAGS::set_rocks_use_partitioned_index_filters(bool value) {
  _internal_set_rocks_use_partitioned_index_filters(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.RocksdbGFLAGS.rocks_use_partitioned_index_filters)
}

// optional bool rocks_use_ribbon_filter = 2;
inline bool RocksdbGFLAGS::_internal_has_rocks_use_ribbon_filter() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool RocksdbGFLAGS::has_rocks_use_ribbon_filter() const {
  return _internal_has_rocks_use_ribbon_filter();
}
inline void RocksdbGFLAGS::clear_rocks_use_ribbon_filter() {
  rocks_use_ribbon_filter_ = false;
  _has_bits_[0] &= ~0x00000002u;
}
inline bool RocksdbGFLAGS::_internal_rocks_use_ribbon_filter() const {
  return rocks_use_ribbon_filter_;
}
inline bool RocksdbGFLAGS::rocks_use_ribbon_filter() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.RocksdbGFLAGS.rocks_use_ribbon_filter)
  return _internal_rocks_use_ribbon_filter();
}
inline void RocksdbGFLAGS::_internal_set_rocks_use_ribbon_filter(bool value) {
  _has_bits_[0] |= 0x00000002u;
  rocks_use_ribbon_filter_ = value;
}
inline void RocksdbGFLAGS::set_rocks_use_ribbon_filter(bool value) {
  _internal_set_rocks_use_ribbon_filter(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.RocksdbGFLAGS.rocks_use_ribbon_filter)
}

// optional bool olap_table_only = 3;
inline bool RocksdbGFLAGS::_internal_has_olap_table_only() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool RocksdbGFLAGS::has_olap_table_only() const {
  return _internal_has_olap_table_only();
}
inline void RocksdbGFLAGS::clear_olap_table_only() {
  olap_table_only_ = false;
  _has_bits_[0] &= ~0x00000004u;
}
inline bool RocksdbGFLAGS::_internal_olap_table_only() const {
  return olap_table_only_;
}
inline bool RocksdbGFLAGS::olap_table_only() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.RocksdbGFLAGS.olap_table_only)
  return _internal_olap_table_only();
}
inline void RocksdbGFLAGS::_internal_set_olap_table_only(bool value) {
  _has_bits_[0] |= 0x00000004u;
  olap_table_only_ = value;
}
inline void RocksdbGFLAGS::set_olap_table_only(bool value) {
  _internal_set_olap_table_only(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.RocksdbGFLAGS.olap_table_only)
}

// optional bool olap_import_mode = 4;
inline bool RocksdbGFLAGS::_internal_has_olap_import_mode() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool RocksdbGFLAGS::has_olap_import_mode() const {
  return _internal_has_olap_import_mode();
}
inline void RocksdbGFLAGS::clear_olap_import_mode() {
  olap_import_mode_ = false;
  _has_bits_[0] &= ~0x00000008u;
}
inline bool RocksdbGFLAGS::_internal_olap_import_mode() const {
  return olap_import_mode_;
}
inline bool RocksdbGFLAGS::olap_import_mode() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.RocksdbGFLAGS.olap_import_mode)
  return _internal_olap_import_mode();
}
inline void RocksdbGFLAGS::_internal_set_olap_import_mode(bool value) {
  _has_bits_[0] |= 0x00000008u;
  olap_import_mode_ = value;
}
inline void RocksdbGFLAGS::set_olap_import_mode(bool value) {
  _internal_set_olap_import_mode(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.RocksdbGFLAGS.olap_import_mode)
}

// optional bool rocks_use_sst_partitioner_fixed_prefix = 5;
inline bool RocksdbGFLAGS::_internal_has_rocks_use_sst_partitioner_fixed_prefix() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool RocksdbGFLAGS::has_rocks_use_sst_partitioner_fixed_prefix() const {
  return _internal_has_rocks_use_sst_partitioner_fixed_prefix();
}
inline void RocksdbGFLAGS::clear_rocks_use_sst_partitioner_fixed_prefix() {
  rocks_use_sst_partitioner_fixed_prefix_ = false;
  _has_bits_[0] &= ~0x00000080u;
}
inline bool RocksdbGFLAGS::_internal_rocks_use_sst_partitioner_fixed_prefix() const {
  return rocks_use_sst_partitioner_fixed_prefix_;
}
inline bool RocksdbGFLAGS::rocks_use_sst_partitioner_fixed_prefix() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.RocksdbGFLAGS.rocks_use_sst_partitioner_fixed_prefix)
  return _internal_rocks_use_sst_partitioner_fixed_prefix();
}
inline void RocksdbGFLAGS::_internal_set_rocks_use_sst_partitioner_fixed_prefix(bool value) {
  _has_bits_[0] |= 0x00000080u;
  rocks_use_sst_partitioner_fixed_prefix_ = value;
}
inline void RocksdbGFLAGS::set_rocks_use_sst_partitioner_fixed_prefix(bool value) {
  _internal_set_rocks_use_sst_partitioner_fixed_prefix(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.RocksdbGFLAGS.rocks_use_sst_partitioner_fixed_prefix)
}

// optional int32 key_point_collector_interval = 6;
inline bool RocksdbGFLAGS::_internal_has_key_point_collector_interval() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool RocksdbGFLAGS::has_key_point_collector_interval() const {
  return _internal_has_key_point_collector_interval();
}
inline void RocksdbGFLAGS::clear_key_point_collector_interval() {
  key_point_collector_interval_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RocksdbGFLAGS::_internal_key_point_collector_interval() const {
  return key_point_collector_interval_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RocksdbGFLAGS::key_point_collector_interval() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.RocksdbGFLAGS.key_point_collector_interval)
  return _internal_key_point_collector_interval();
}
inline void RocksdbGFLAGS::_internal_set_key_point_collector_interval(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000010u;
  key_point_collector_interval_ = value;
}
inline void RocksdbGFLAGS::set_key_point_collector_interval(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_key_point_collector_interval(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.RocksdbGFLAGS.key_point_collector_interval)
}

// optional int64 rocks_block_cache_size_mb = 7;
inline bool RocksdbGFLAGS::_internal_has_rocks_block_cache_size_mb() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool RocksdbGFLAGS::has_rocks_block_cache_size_mb() const {
  return _internal_has_rocks_block_cache_size_mb();
}
inline void RocksdbGFLAGS::clear_rocks_block_cache_size_mb() {
  rocks_block_cache_size_mb_ = int64_t{0};
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 RocksdbGFLAGS::_internal_rocks_block_cache_size_mb() const {
  return rocks_block_cache_size_mb_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 RocksdbGFLAGS::rocks_block_cache_size_mb() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.RocksdbGFLAGS.rocks_block_cache_size_mb)
  return _internal_rocks_block_cache_size_mb();
}
inline void RocksdbGFLAGS::_internal_set_rocks_block_cache_size_mb(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000020u;
  rocks_block_cache_size_mb_ = value;
}
inline void RocksdbGFLAGS::set_rocks_block_cache_size_mb(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_rocks_block_cache_size_mb(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.RocksdbGFLAGS.rocks_block_cache_size_mb)
}

// optional double rocks_high_pri_pool_ratio = 8;
inline bool RocksdbGFLAGS::_internal_has_rocks_high_pri_pool_ratio() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool RocksdbGFLAGS::has_rocks_high_pri_pool_ratio() const {
  return _internal_has_rocks_high_pri_pool_ratio();
}
inline void RocksdbGFLAGS::clear_rocks_high_pri_pool_ratio() {
  rocks_high_pri_pool_ratio_ = 0;
  _has_bits_[0] &= ~0x00000040u;
}
inline double RocksdbGFLAGS::_internal_rocks_high_pri_pool_ratio() const {
  return rocks_high_pri_pool_ratio_;
}
inline double RocksdbGFLAGS::rocks_high_pri_pool_ratio() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.RocksdbGFLAGS.rocks_high_pri_pool_ratio)
  return _internal_rocks_high_pri_pool_ratio();
}
inline void RocksdbGFLAGS::_internal_set_rocks_high_pri_pool_ratio(double value) {
  _has_bits_[0] |= 0x00000040u;
  rocks_high_pri_pool_ratio_ = value;
}
inline void RocksdbGFLAGS::set_rocks_high_pri_pool_ratio(double value) {
  _internal_set_rocks_high_pri_pool_ratio(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.RocksdbGFLAGS.rocks_high_pri_pool_ratio)
}

// optional bool rocks_use_hyper_clock_cache = 9;
inline bool RocksdbGFLAGS::_internal_has_rocks_use_hyper_clock_cache() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool RocksdbGFLAGS::has_rocks_use_hyper_clock_cache() const {
  return _internal_has_rocks_use_hyper_clock_cache();
}
inline void RocksdbGFLAGS::clear_rocks_use_hyper_clock_cache() {
  rocks_use_hyper_clock_cache_ = false;
  _has_bits_[0] &= ~0x00000100u;
}
inline bool RocksdbGFLAGS::_internal_rocks_use_hyper_clock_cache() const {
  return rocks_use_hyper_clock_cache_;
}
inline bool RocksdbGFLAGS::rocks_use_hyper_clock_cache() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.RocksdbGFLAGS.rocks_use_hyper_clock_cache)
  return _internal_rocks_use_hyper_clock_cache();
}
inline void RocksdbGFLAGS::_internal_set_rocks_use_hyper_clock_cache(bool value) {
  _has_bits_[0] |= 0x00000100u;
  rocks_use_hyper_clock_cache_ = value;
}
inline void RocksdbGFLAGS::set_rocks_use_hyper_clock_cache(bool value) {
  _internal_set_rocks_use_hyper_clock_cache(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.RocksdbGFLAGS.rocks_use_hyper_clock_cache)
}

// optional int32 rocks_block_size = 10;
inline bool RocksdbGFLAGS::_internal_has_rocks_block_size() const {
  bool value = (_has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool RocksdbGFLAGS::has_rocks_block_size() const {
  return _internal_has_rocks_block_size();
}
inline void RocksdbGFLAGS::clear_rocks_block_size() {
  rocks_block_size_ = 0;
  _has_bits_[0] &= ~0x00000200u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RocksdbGFLAGS::_internal_rocks_block_size() const {
  return rocks_block_size_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RocksdbGFLAGS::rocks_block_size() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.RocksdbGFLAGS.rocks_block_size)
  return _internal_rocks_block_size();
}
inline void RocksdbGFLAGS::_internal_set_rocks_block_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000200u;
  rocks_block_size_ = value;
}
inline void RocksdbGFLAGS::set_rocks_block_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_rocks_block_size(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.RocksdbGFLAGS.rocks_block_size)
}

// -------------------------------------------------------------------

// RemoteCompactionRequest

// optional string remote_compaction_id = 1;
inline bool RemoteCompactionRequest::_internal_has_remote_compaction_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool RemoteCompactionRequest::has_remote_compaction_id() const {
  return _internal_has_remote_compaction_id();
}
inline void RemoteCompactionRequest::clear_remote_compaction_id() {
  remote_compaction_id_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& RemoteCompactionRequest::remote_compaction_id() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.RemoteCompactionRequest.remote_compaction_id)
  return _internal_remote_compaction_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RemoteCompactionRequest::set_remote_compaction_id(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 remote_compaction_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:baikaldb.pb.RemoteCompactionRequest.remote_compaction_id)
}
inline std::string* RemoteCompactionRequest::mutable_remote_compaction_id() {
  std::string* _s = _internal_mutable_remote_compaction_id();
  // @@protoc_insertion_point(field_mutable:baikaldb.pb.RemoteCompactionRequest.remote_compaction_id)
  return _s;
}
inline const std::string& RemoteCompactionRequest::_internal_remote_compaction_id() const {
  return remote_compaction_id_.Get();
}
inline void RemoteCompactionRequest::_internal_set_remote_compaction_id(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  remote_compaction_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* RemoteCompactionRequest::_internal_mutable_remote_compaction_id() {
  _has_bits_[0] |= 0x00000001u;
  return remote_compaction_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* RemoteCompactionRequest::release_remote_compaction_id() {
  // @@protoc_insertion_point(field_release:baikaldb.pb.RemoteCompactionRequest.remote_compaction_id)
  if (!_internal_has_remote_compaction_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return remote_compaction_id_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void RemoteCompactionRequest::set_allocated_remote_compaction_id(std::string* remote_compaction_id) {
  if (remote_compaction_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  remote_compaction_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), remote_compaction_id,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:baikaldb.pb.RemoteCompactionRequest.remote_compaction_id)
}

// optional bytes compaction_input_binary = 2;
inline bool RemoteCompactionRequest::_internal_has_compaction_input_binary() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool RemoteCompactionRequest::has_compaction_input_binary() const {
  return _internal_has_compaction_input_binary();
}
inline void RemoteCompactionRequest::clear_compaction_input_binary() {
  compaction_input_binary_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& RemoteCompactionRequest::compaction_input_binary() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.RemoteCompactionRequest.compaction_input_binary)
  return _internal_compaction_input_binary();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RemoteCompactionRequest::set_compaction_input_binary(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000002u;
 compaction_input_binary_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:baikaldb.pb.RemoteCompactionRequest.compaction_input_binary)
}
inline std::string* RemoteCompactionRequest::mutable_compaction_input_binary() {
  std::string* _s = _internal_mutable_compaction_input_binary();
  // @@protoc_insertion_point(field_mutable:baikaldb.pb.RemoteCompactionRequest.compaction_input_binary)
  return _s;
}
inline const std::string& RemoteCompactionRequest::_internal_compaction_input_binary() const {
  return compaction_input_binary_.Get();
}
inline void RemoteCompactionRequest::_internal_set_compaction_input_binary(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  compaction_input_binary_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* RemoteCompactionRequest::_internal_mutable_compaction_input_binary() {
  _has_bits_[0] |= 0x00000002u;
  return compaction_input_binary_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* RemoteCompactionRequest::release_compaction_input_binary() {
  // @@protoc_insertion_point(field_release:baikaldb.pb.RemoteCompactionRequest.compaction_input_binary)
  if (!_internal_has_compaction_input_binary()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return compaction_input_binary_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void RemoteCompactionRequest::set_allocated_compaction_input_binary(std::string* compaction_input_binary) {
  if (compaction_input_binary != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  compaction_input_binary_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), compaction_input_binary,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:baikaldb.pb.RemoteCompactionRequest.compaction_input_binary)
}

// optional string address = 3;
inline bool RemoteCompactionRequest::_internal_has_address() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool RemoteCompactionRequest::has_address() const {
  return _internal_has_address();
}
inline void RemoteCompactionRequest::clear_address() {
  address_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& RemoteCompactionRequest::address() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.RemoteCompactionRequest.address)
  return _internal_address();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RemoteCompactionRequest::set_address(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000004u;
 address_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:baikaldb.pb.RemoteCompactionRequest.address)
}
inline std::string* RemoteCompactionRequest::mutable_address() {
  std::string* _s = _internal_mutable_address();
  // @@protoc_insertion_point(field_mutable:baikaldb.pb.RemoteCompactionRequest.address)
  return _s;
}
inline const std::string& RemoteCompactionRequest::_internal_address() const {
  return address_.Get();
}
inline void RemoteCompactionRequest::_internal_set_address(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  address_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* RemoteCompactionRequest::_internal_mutable_address() {
  _has_bits_[0] |= 0x00000004u;
  return address_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* RemoteCompactionRequest::release_address() {
  // @@protoc_insertion_point(field_release:baikaldb.pb.RemoteCompactionRequest.address)
  if (!_internal_has_address()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return address_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void RemoteCompactionRequest::set_allocated_address(std::string* address) {
  if (address != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  address_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), address,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:baikaldb.pb.RemoteCompactionRequest.address)
}

// optional string cf_name = 4;
inline bool RemoteCompactionRequest::_internal_has_cf_name() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool RemoteCompactionRequest::has_cf_name() const {
  return _internal_has_cf_name();
}
inline void RemoteCompactionRequest::clear_cf_name() {
  cf_name_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000008u;
}
inline const std::string& RemoteCompactionRequest::cf_name() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.RemoteCompactionRequest.cf_name)
  return _internal_cf_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RemoteCompactionRequest::set_cf_name(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000008u;
 cf_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:baikaldb.pb.RemoteCompactionRequest.cf_name)
}
inline std::string* RemoteCompactionRequest::mutable_cf_name() {
  std::string* _s = _internal_mutable_cf_name();
  // @@protoc_insertion_point(field_mutable:baikaldb.pb.RemoteCompactionRequest.cf_name)
  return _s;
}
inline const std::string& RemoteCompactionRequest::_internal_cf_name() const {
  return cf_name_.Get();
}
inline void RemoteCompactionRequest::_internal_set_cf_name(const std::string& value) {
  _has_bits_[0] |= 0x00000008u;
  cf_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* RemoteCompactionRequest::_internal_mutable_cf_name() {
  _has_bits_[0] |= 0x00000008u;
  return cf_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* RemoteCompactionRequest::release_cf_name() {
  // @@protoc_insertion_point(field_release:baikaldb.pb.RemoteCompactionRequest.cf_name)
  if (!_internal_has_cf_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000008u;
  return cf_name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void RemoteCompactionRequest::set_allocated_cf_name(std::string* cf_name) {
  if (cf_name != nullptr) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  cf_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), cf_name,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:baikaldb.pb.RemoteCompactionRequest.cf_name)
}

// optional .baikaldb.pb.RocksdbGFLAGS rocksdb_gflags = 5;
inline bool RemoteCompactionRequest::_internal_has_rocksdb_gflags() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  PROTOBUF_ASSUME(!value || rocksdb_gflags_ != nullptr);
  return value;
}
inline bool RemoteCompactionRequest::has_rocksdb_gflags() const {
  return _internal_has_rocksdb_gflags();
}
inline void RemoteCompactionRequest::clear_rocksdb_gflags() {
  if (rocksdb_gflags_ != nullptr) rocksdb_gflags_->Clear();
  _has_bits_[0] &= ~0x00000010u;
}
inline const ::baikaldb::pb::RocksdbGFLAGS& RemoteCompactionRequest::_internal_rocksdb_gflags() const {
  const ::baikaldb::pb::RocksdbGFLAGS* p = rocksdb_gflags_;
  return p != nullptr ? *p : reinterpret_cast<const ::baikaldb::pb::RocksdbGFLAGS&>(
      ::baikaldb::pb::_RocksdbGFLAGS_default_instance_);
}
inline const ::baikaldb::pb::RocksdbGFLAGS& RemoteCompactionRequest::rocksdb_gflags() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.RemoteCompactionRequest.rocksdb_gflags)
  return _internal_rocksdb_gflags();
}
inline void RemoteCompactionRequest::unsafe_arena_set_allocated_rocksdb_gflags(
    ::baikaldb::pb::RocksdbGFLAGS* rocksdb_gflags) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(rocksdb_gflags_);
  }
  rocksdb_gflags_ = rocksdb_gflags;
  if (rocksdb_gflags) {
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:baikaldb.pb.RemoteCompactionRequest.rocksdb_gflags)
}
inline ::baikaldb::pb::RocksdbGFLAGS* RemoteCompactionRequest::release_rocksdb_gflags() {
  _has_bits_[0] &= ~0x00000010u;
  ::baikaldb::pb::RocksdbGFLAGS* temp = rocksdb_gflags_;
  rocksdb_gflags_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::baikaldb::pb::RocksdbGFLAGS* RemoteCompactionRequest::unsafe_arena_release_rocksdb_gflags() {
  // @@protoc_insertion_point(field_release:baikaldb.pb.RemoteCompactionRequest.rocksdb_gflags)
  _has_bits_[0] &= ~0x00000010u;
  ::baikaldb::pb::RocksdbGFLAGS* temp = rocksdb_gflags_;
  rocksdb_gflags_ = nullptr;
  return temp;
}
inline ::baikaldb::pb::RocksdbGFLAGS* RemoteCompactionRequest::_internal_mutable_rocksdb_gflags() {
  _has_bits_[0] |= 0x00000010u;
  if (rocksdb_gflags_ == nullptr) {
    auto* p = CreateMaybeMessage<::baikaldb::pb::RocksdbGFLAGS>(GetArenaForAllocation());
    rocksdb_gflags_ = p;
  }
  return rocksdb_gflags_;
}
inline ::baikaldb::pb::RocksdbGFLAGS* RemoteCompactionRequest::mutable_rocksdb_gflags() {
  ::baikaldb::pb::RocksdbGFLAGS* _msg = _internal_mutable_rocksdb_gflags();
  // @@protoc_insertion_point(field_mutable:baikaldb.pb.RemoteCompactionRequest.rocksdb_gflags)
  return _msg;
}
inline void RemoteCompactionRequest::set_allocated_rocksdb_gflags(::baikaldb::pb::RocksdbGFLAGS* rocksdb_gflags) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete rocksdb_gflags_;
  }
  if (rocksdb_gflags) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::baikaldb::pb::RocksdbGFLAGS>::GetOwningArena(rocksdb_gflags);
    if (message_arena != submessage_arena) {
      rocksdb_gflags = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, rocksdb_gflags, submessage_arena);
    }
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  rocksdb_gflags_ = rocksdb_gflags;
  // @@protoc_insertion_point(field_set_allocated:baikaldb.pb.RemoteCompactionRequest.rocksdb_gflags)
}

// -------------------------------------------------------------------

// RemoteCompactionResponse

// optional .baikaldb.pb.ErrCode errcode = 1;
inline bool RemoteCompactionResponse::_internal_has_errcode() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool RemoteCompactionResponse::has_errcode() const {
  return _internal_has_errcode();
}
inline void RemoteCompactionResponse::clear_errcode() {
  errcode_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::baikaldb::pb::ErrCode RemoteCompactionResponse::_internal_errcode() const {
  return static_cast< ::baikaldb::pb::ErrCode >(errcode_);
}
inline ::baikaldb::pb::ErrCode RemoteCompactionResponse::errcode() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.RemoteCompactionResponse.errcode)
  return _internal_errcode();
}
inline void RemoteCompactionResponse::_internal_set_errcode(::baikaldb::pb::ErrCode value) {
  assert(::baikaldb::pb::ErrCode_IsValid(value));
  _has_bits_[0] |= 0x00000002u;
  errcode_ = value;
}
inline void RemoteCompactionResponse::set_errcode(::baikaldb::pb::ErrCode value) {
  _internal_set_errcode(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.RemoteCompactionResponse.errcode)
}

// optional bytes compaction_result_binary = 2;
inline bool RemoteCompactionResponse::_internal_has_compaction_result_binary() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool RemoteCompactionResponse::has_compaction_result_binary() const {
  return _internal_has_compaction_result_binary();
}
inline void RemoteCompactionResponse::clear_compaction_result_binary() {
  compaction_result_binary_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& RemoteCompactionResponse::compaction_result_binary() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.RemoteCompactionResponse.compaction_result_binary)
  return _internal_compaction_result_binary();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RemoteCompactionResponse::set_compaction_result_binary(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 compaction_result_binary_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:baikaldb.pb.RemoteCompactionResponse.compaction_result_binary)
}
inline std::string* RemoteCompactionResponse::mutable_compaction_result_binary() {
  std::string* _s = _internal_mutable_compaction_result_binary();
  // @@protoc_insertion_point(field_mutable:baikaldb.pb.RemoteCompactionResponse.compaction_result_binary)
  return _s;
}
inline const std::string& RemoteCompactionResponse::_internal_compaction_result_binary() const {
  return compaction_result_binary_.Get();
}
inline void RemoteCompactionResponse::_internal_set_compaction_result_binary(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  compaction_result_binary_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* RemoteCompactionResponse::_internal_mutable_compaction_result_binary() {
  _has_bits_[0] |= 0x00000001u;
  return compaction_result_binary_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* RemoteCompactionResponse::release_compaction_result_binary() {
  // @@protoc_insertion_point(field_release:baikaldb.pb.RemoteCompactionResponse.compaction_result_binary)
  if (!_internal_has_compaction_result_binary()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return compaction_result_binary_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void RemoteCompactionResponse::set_allocated_compaction_result_binary(std::string* compaction_result_binary) {
  if (compaction_result_binary != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  compaction_result_binary_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), compaction_result_binary,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:baikaldb.pb.RemoteCompactionResponse.compaction_result_binary)
}

// repeated .baikaldb.pb.CompactionFileInfo output_file_info = 3;
inline int RemoteCompactionResponse::_internal_output_file_info_size() const {
  return output_file_info_.size();
}
inline int RemoteCompactionResponse::output_file_info_size() const {
  return _internal_output_file_info_size();
}
inline ::baikaldb::pb::CompactionFileInfo* RemoteCompactionResponse::mutable_output_file_info(int index) {
  // @@protoc_insertion_point(field_mutable:baikaldb.pb.RemoteCompactionResponse.output_file_info)
  return output_file_info_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::baikaldb::pb::CompactionFileInfo >*
RemoteCompactionResponse::mutable_output_file_info() {
  // @@protoc_insertion_point(field_mutable_list:baikaldb.pb.RemoteCompactionResponse.output_file_info)
  return &output_file_info_;
}
inline const ::baikaldb::pb::CompactionFileInfo& RemoteCompactionResponse::_internal_output_file_info(int index) const {
  return output_file_info_.Get(index);
}
inline const ::baikaldb::pb::CompactionFileInfo& RemoteCompactionResponse::output_file_info(int index) const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.RemoteCompactionResponse.output_file_info)
  return _internal_output_file_info(index);
}
inline ::baikaldb::pb::CompactionFileInfo* RemoteCompactionResponse::_internal_add_output_file_info() {
  return output_file_info_.Add();
}
inline ::baikaldb::pb::CompactionFileInfo* RemoteCompactionResponse::add_output_file_info() {
  ::baikaldb::pb::CompactionFileInfo* _add = _internal_add_output_file_info();
  // @@protoc_insertion_point(field_add:baikaldb.pb.RemoteCompactionResponse.output_file_info)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::baikaldb::pb::CompactionFileInfo >&
RemoteCompactionResponse::output_file_info() const {
  // @@protoc_insertion_point(field_list:baikaldb.pb.RemoteCompactionResponse.output_file_info)
  return output_file_info_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace baikaldb

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_compaction_2einterface_2eproto
