// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db.interface.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_db_2einterface_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_db_2einterface_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3018000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3018000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
#include "meta.interface.pb.h"
#include "plan.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_db_2einterface_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_db_2einterface_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_db_2einterface_2eproto;
namespace baikaldb {
namespace pb {
class DAGFragmentRequest;
struct DAGFragmentRequestDefaultTypeInternal;
extern DAGFragmentRequestDefaultTypeInternal _DAGFragmentRequest_default_instance_;
class DbResponse;
struct DbResponseDefaultTypeInternal;
extern DbResponseDefaultTypeInternal _DbResponse_default_instance_;
class QueryStat;
struct QueryStatDefaultTypeInternal;
extern QueryStatDefaultTypeInternal _QueryStat_default_instance_;
class TransmitDataParam;
struct TransmitDataParamDefaultTypeInternal;
extern TransmitDataParamDefaultTypeInternal _TransmitDataParam_default_instance_;
}  // namespace pb
}  // namespace baikaldb
PROTOBUF_NAMESPACE_OPEN
template<> ::baikaldb::pb::DAGFragmentRequest* Arena::CreateMaybeMessage<::baikaldb::pb::DAGFragmentRequest>(Arena*);
template<> ::baikaldb::pb::DbResponse* Arena::CreateMaybeMessage<::baikaldb::pb::DbResponse>(Arena*);
template<> ::baikaldb::pb::QueryStat* Arena::CreateMaybeMessage<::baikaldb::pb::QueryStat>(Arena*);
template<> ::baikaldb::pb::TransmitDataParam* Arena::CreateMaybeMessage<::baikaldb::pb::TransmitDataParam>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace baikaldb {
namespace pb {

enum ExchangeState : int {
  ES_DOING = 1,
  ES_EOF = 2,
  ES_EXEC_FAIL = 3,
  ES_VERSION_OLD = 4
};
bool ExchangeState_IsValid(int value);
constexpr ExchangeState ExchangeState_MIN = ES_DOING;
constexpr ExchangeState ExchangeState_MAX = ES_VERSION_OLD;
constexpr int ExchangeState_ARRAYSIZE = ExchangeState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ExchangeState_descriptor();
template<typename T>
inline const std::string& ExchangeState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ExchangeState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ExchangeState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ExchangeState_descriptor(), enum_t_value);
}
inline bool ExchangeState_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ExchangeState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ExchangeState>(
    ExchangeState_descriptor(), name, value);
}
enum FragmentOpType : int {
  OP_FRAGMENT_START = 0,
  OP_FRAGMENT_STOP = 1
};
bool FragmentOpType_IsValid(int value);
constexpr FragmentOpType FragmentOpType_MIN = OP_FRAGMENT_START;
constexpr FragmentOpType FragmentOpType_MAX = OP_FRAGMENT_STOP;
constexpr int FragmentOpType_ARRAYSIZE = FragmentOpType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* FragmentOpType_descriptor();
template<typename T>
inline const std::string& FragmentOpType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, FragmentOpType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function FragmentOpType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    FragmentOpType_descriptor(), enum_t_value);
}
inline bool FragmentOpType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, FragmentOpType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<FragmentOpType>(
    FragmentOpType_descriptor(), name, value);
}
// ===================================================================

class QueryStat final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:baikaldb.pb.QueryStat) */ {
 public:
  inline QueryStat() : QueryStat(nullptr) {}
  ~QueryStat() override;
  explicit constexpr QueryStat(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  QueryStat(const QueryStat& from);
  QueryStat(QueryStat&& from) noexcept
    : QueryStat() {
    *this = ::std::move(from);
  }

  inline QueryStat& operator=(const QueryStat& from) {
    CopyFrom(from);
    return *this;
  }
  inline QueryStat& operator=(QueryStat&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const QueryStat& default_instance() {
    return *internal_default_instance();
  }
  static inline const QueryStat* internal_default_instance() {
    return reinterpret_cast<const QueryStat*>(
               &_QueryStat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(QueryStat& a, QueryStat& b) {
    a.Swap(&b);
  }
  inline void Swap(QueryStat* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QueryStat* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline QueryStat* New() const final {
    return new QueryStat();
  }

  QueryStat* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<QueryStat>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const QueryStat& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const QueryStat& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(QueryStat* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "baikaldb.pb.QueryStat";
  }
  protected:
  explicit QueryStat(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNumAffectedRowsFieldNumber = 1,
    kNumReturnedRowsFieldNumber = 2,
    kNumScanRowsFieldNumber = 3,
    kNumFilterRowsFieldNumber = 4,
    kRegionCountFieldNumber = 5,
    kDbHandleRowsFieldNumber = 6,
    kDbHandleBytesFieldNumber = 7,
  };
  // optional int64 num_affected_rows = 1;
  bool has_num_affected_rows() const;
  private:
  bool _internal_has_num_affected_rows() const;
  public:
  void clear_num_affected_rows();
  ::PROTOBUF_NAMESPACE_ID::int64 num_affected_rows() const;
  void set_num_affected_rows(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_num_affected_rows() const;
  void _internal_set_num_affected_rows(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // optional int64 num_returned_rows = 2;
  bool has_num_returned_rows() const;
  private:
  bool _internal_has_num_returned_rows() const;
  public:
  void clear_num_returned_rows();
  ::PROTOBUF_NAMESPACE_ID::int64 num_returned_rows() const;
  void set_num_returned_rows(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_num_returned_rows() const;
  void _internal_set_num_returned_rows(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // optional int64 num_scan_rows = 3;
  bool has_num_scan_rows() const;
  private:
  bool _internal_has_num_scan_rows() const;
  public:
  void clear_num_scan_rows();
  ::PROTOBUF_NAMESPACE_ID::int64 num_scan_rows() const;
  void set_num_scan_rows(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_num_scan_rows() const;
  void _internal_set_num_scan_rows(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // optional int64 num_filter_rows = 4;
  bool has_num_filter_rows() const;
  private:
  bool _internal_has_num_filter_rows() const;
  public:
  void clear_num_filter_rows();
  ::PROTOBUF_NAMESPACE_ID::int64 num_filter_rows() const;
  void set_num_filter_rows(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_num_filter_rows() const;
  void _internal_set_num_filter_rows(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // optional int64 region_count = 5;
  bool has_region_count() const;
  private:
  bool _internal_has_region_count() const;
  public:
  void clear_region_count();
  ::PROTOBUF_NAMESPACE_ID::int64 region_count() const;
  void set_region_count(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_region_count() const;
  void _internal_set_region_count(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // optional int64 db_handle_rows = 6;
  bool has_db_handle_rows() const;
  private:
  bool _internal_has_db_handle_rows() const;
  public:
  void clear_db_handle_rows();
  ::PROTOBUF_NAMESPACE_ID::int64 db_handle_rows() const;
  void set_db_handle_rows(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_db_handle_rows() const;
  void _internal_set_db_handle_rows(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // optional int64 db_handle_bytes = 7;
  bool has_db_handle_bytes() const;
  private:
  bool _internal_has_db_handle_bytes() const;
  public:
  void clear_db_handle_bytes();
  ::PROTOBUF_NAMESPACE_ID::int64 db_handle_bytes() const;
  void set_db_handle_bytes(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_db_handle_bytes() const;
  void _internal_set_db_handle_bytes(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:baikaldb.pb.QueryStat)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::int64 num_affected_rows_;
  ::PROTOBUF_NAMESPACE_ID::int64 num_returned_rows_;
  ::PROTOBUF_NAMESPACE_ID::int64 num_scan_rows_;
  ::PROTOBUF_NAMESPACE_ID::int64 num_filter_rows_;
  ::PROTOBUF_NAMESPACE_ID::int64 region_count_;
  ::PROTOBUF_NAMESPACE_ID::int64 db_handle_rows_;
  ::PROTOBUF_NAMESPACE_ID::int64 db_handle_bytes_;
  friend struct ::TableStruct_db_2einterface_2eproto;
};
// -------------------------------------------------------------------

class TransmitDataParam final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:baikaldb.pb.TransmitDataParam) */ {
 public:
  inline TransmitDataParam() : TransmitDataParam(nullptr) {}
  ~TransmitDataParam() override;
  explicit constexpr TransmitDataParam(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TransmitDataParam(const TransmitDataParam& from);
  TransmitDataParam(TransmitDataParam&& from) noexcept
    : TransmitDataParam() {
    *this = ::std::move(from);
  }

  inline TransmitDataParam& operator=(const TransmitDataParam& from) {
    CopyFrom(from);
    return *this;
  }
  inline TransmitDataParam& operator=(TransmitDataParam&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TransmitDataParam& default_instance() {
    return *internal_default_instance();
  }
  static inline const TransmitDataParam* internal_default_instance() {
    return reinterpret_cast<const TransmitDataParam*>(
               &_TransmitDataParam_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(TransmitDataParam& a, TransmitDataParam& b) {
    a.Swap(&b);
  }
  inline void Swap(TransmitDataParam* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TransmitDataParam* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TransmitDataParam* New() const final {
    return new TransmitDataParam();
  }

  TransmitDataParam* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TransmitDataParam>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TransmitDataParam& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const TransmitDataParam& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TransmitDataParam* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "baikaldb.pb.TransmitDataParam";
  }
  protected:
  explicit TransmitDataParam(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRegionInfosFieldNumber = 9,
    kVectorizedSchemaFieldNumber = 12,
    kQueryStatFieldNumber = 11,
    kLogIdFieldNumber = 2,
    kSenderFragmentInstanceIdFieldNumber = 3,
    kReceiverFragmentInstanceIdFieldNumber = 4,
    kRegionIdFieldNumber = 6,
    kRegionVersionFieldNumber = 7,
    kReceiverNodeIdFieldNumber = 5,
    kIsMergeFieldNumber = 8,
    kIsLocalPassThroughFieldNumber = 13,
    kRecordBatchSeqFieldNumber = 10,
    kRecordBatchRowsFieldNumber = 14,
    kExchangeStateFieldNumber = 1,
  };
  // repeated .baikaldb.pb.RegionInfo region_infos = 9;
  int region_infos_size() const;
  private:
  int _internal_region_infos_size() const;
  public:
  void clear_region_infos();
  ::baikaldb::pb::RegionInfo* mutable_region_infos(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::baikaldb::pb::RegionInfo >*
      mutable_region_infos();
  private:
  const ::baikaldb::pb::RegionInfo& _internal_region_infos(int index) const;
  ::baikaldb::pb::RegionInfo* _internal_add_region_infos();
  public:
  const ::baikaldb::pb::RegionInfo& region_infos(int index) const;
  ::baikaldb::pb::RegionInfo* add_region_infos();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::baikaldb::pb::RegionInfo >&
      region_infos() const;

  // optional bytes vectorized_schema = 12;
  bool has_vectorized_schema() const;
  private:
  bool _internal_has_vectorized_schema() const;
  public:
  void clear_vectorized_schema();
  const std::string& vectorized_schema() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_vectorized_schema(ArgT0&& arg0, ArgT... args);
  std::string* mutable_vectorized_schema();
  PROTOBUF_MUST_USE_RESULT std::string* release_vectorized_schema();
  void set_allocated_vectorized_schema(std::string* vectorized_schema);
  private:
  const std::string& _internal_vectorized_schema() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_vectorized_schema(const std::string& value);
  std::string* _internal_mutable_vectorized_schema();
  public:

  // optional .baikaldb.pb.QueryStat query_stat = 11;
  bool has_query_stat() const;
  private:
  bool _internal_has_query_stat() const;
  public:
  void clear_query_stat();
  const ::baikaldb::pb::QueryStat& query_stat() const;
  PROTOBUF_MUST_USE_RESULT ::baikaldb::pb::QueryStat* release_query_stat();
  ::baikaldb::pb::QueryStat* mutable_query_stat();
  void set_allocated_query_stat(::baikaldb::pb::QueryStat* query_stat);
  private:
  const ::baikaldb::pb::QueryStat& _internal_query_stat() const;
  ::baikaldb::pb::QueryStat* _internal_mutable_query_stat();
  public:
  void unsafe_arena_set_allocated_query_stat(
      ::baikaldb::pb::QueryStat* query_stat);
  ::baikaldb::pb::QueryStat* unsafe_arena_release_query_stat();

  // required uint64 log_id = 2;
  bool has_log_id() const;
  private:
  bool _internal_has_log_id() const;
  public:
  void clear_log_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 log_id() const;
  void set_log_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_log_id() const;
  void _internal_set_log_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // required uint64 sender_fragment_instance_id = 3;
  bool has_sender_fragment_instance_id() const;
  private:
  bool _internal_has_sender_fragment_instance_id() const;
  public:
  void clear_sender_fragment_instance_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 sender_fragment_instance_id() const;
  void set_sender_fragment_instance_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_sender_fragment_instance_id() const;
  void _internal_set_sender_fragment_instance_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // required uint64 receiver_fragment_instance_id = 4;
  bool has_receiver_fragment_instance_id() const;
  private:
  bool _internal_has_receiver_fragment_instance_id() const;
  public:
  void clear_receiver_fragment_instance_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 receiver_fragment_instance_id() const;
  void set_receiver_fragment_instance_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_receiver_fragment_instance_id() const;
  void _internal_set_receiver_fragment_instance_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional int64 region_id = 6;
  bool has_region_id() const;
  private:
  bool _internal_has_region_id() const;
  public:
  void clear_region_id();
  ::PROTOBUF_NAMESPACE_ID::int64 region_id() const;
  void set_region_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_region_id() const;
  void _internal_set_region_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // optional int64 region_version = 7;
  bool has_region_version() const;
  private:
  bool _internal_has_region_version() const;
  public:
  void clear_region_version();
  ::PROTOBUF_NAMESPACE_ID::int64 region_version() const;
  void set_region_version(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_region_version() const;
  void _internal_set_region_version(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // required int32 receiver_node_id = 5;
  bool has_receiver_node_id() const;
  private:
  bool _internal_has_receiver_node_id() const;
  public:
  void clear_receiver_node_id();
  ::PROTOBUF_NAMESPACE_ID::int32 receiver_node_id() const;
  void set_receiver_node_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_receiver_node_id() const;
  void _internal_set_receiver_node_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional bool is_merge = 8;
  bool has_is_merge() const;
  private:
  bool _internal_has_is_merge() const;
  public:
  void clear_is_merge();
  bool is_merge() const;
  void set_is_merge(bool value);
  private:
  bool _internal_is_merge() const;
  void _internal_set_is_merge(bool value);
  public:

  // required bool is_local_pass_through = 13;
  bool has_is_local_pass_through() const;
  private:
  bool _internal_has_is_local_pass_through() const;
  public:
  void clear_is_local_pass_through();
  bool is_local_pass_through() const;
  void set_is_local_pass_through(bool value);
  private:
  bool _internal_is_local_pass_through() const;
  void _internal_set_is_local_pass_through(bool value);
  public:

  // optional int64 record_batch_seq = 10;
  bool has_record_batch_seq() const;
  private:
  bool _internal_has_record_batch_seq() const;
  public:
  void clear_record_batch_seq();
  ::PROTOBUF_NAMESPACE_ID::int64 record_batch_seq() const;
  void set_record_batch_seq(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_record_batch_seq() const;
  void _internal_set_record_batch_seq(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // optional int64 record_batch_rows = 14;
  bool has_record_batch_rows() const;
  private:
  bool _internal_has_record_batch_rows() const;
  public:
  void clear_record_batch_rows();
  ::PROTOBUF_NAMESPACE_ID::int64 record_batch_rows() const;
  void set_record_batch_rows(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_record_batch_rows() const;
  void _internal_set_record_batch_rows(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // required .baikaldb.pb.ExchangeState exchange_state = 1;
  bool has_exchange_state() const;
  private:
  bool _internal_has_exchange_state() const;
  public:
  void clear_exchange_state();
  ::baikaldb::pb::ExchangeState exchange_state() const;
  void set_exchange_state(::baikaldb::pb::ExchangeState value);
  private:
  ::baikaldb::pb::ExchangeState _internal_exchange_state() const;
  void _internal_set_exchange_state(::baikaldb::pb::ExchangeState value);
  public:

  // @@protoc_insertion_point(class_scope:baikaldb.pb.TransmitDataParam)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::baikaldb::pb::RegionInfo > region_infos_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr vectorized_schema_;
  ::baikaldb::pb::QueryStat* query_stat_;
  ::PROTOBUF_NAMESPACE_ID::uint64 log_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 sender_fragment_instance_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 receiver_fragment_instance_id_;
  ::PROTOBUF_NAMESPACE_ID::int64 region_id_;
  ::PROTOBUF_NAMESPACE_ID::int64 region_version_;
  ::PROTOBUF_NAMESPACE_ID::int32 receiver_node_id_;
  bool is_merge_;
  bool is_local_pass_through_;
  ::PROTOBUF_NAMESPACE_ID::int64 record_batch_seq_;
  ::PROTOBUF_NAMESPACE_ID::int64 record_batch_rows_;
  int exchange_state_;
  friend struct ::TableStruct_db_2einterface_2eproto;
};
// -------------------------------------------------------------------

class DbResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:baikaldb.pb.DbResponse) */ {
 public:
  inline DbResponse() : DbResponse(nullptr) {}
  ~DbResponse() override;
  explicit constexpr DbResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DbResponse(const DbResponse& from);
  DbResponse(DbResponse&& from) noexcept
    : DbResponse() {
    *this = ::std::move(from);
  }

  inline DbResponse& operator=(const DbResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline DbResponse& operator=(DbResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DbResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const DbResponse* internal_default_instance() {
    return reinterpret_cast<const DbResponse*>(
               &_DbResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(DbResponse& a, DbResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(DbResponse* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DbResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DbResponse* New() const final {
    return new DbResponse();
  }

  DbResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DbResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DbResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const DbResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DbResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "baikaldb.pb.DbResponse";
  }
  protected:
  explicit DbResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrmsgFieldNumber = 2,
    kErrcodeFieldNumber = 1,
  };
  // optional string errmsg = 2;
  bool has_errmsg() const;
  private:
  bool _internal_has_errmsg() const;
  public:
  void clear_errmsg();
  const std::string& errmsg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_errmsg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_errmsg();
  PROTOBUF_MUST_USE_RESULT std::string* release_errmsg();
  void set_allocated_errmsg(std::string* errmsg);
  private:
  const std::string& _internal_errmsg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_errmsg(const std::string& value);
  std::string* _internal_mutable_errmsg();
  public:

  // required .baikaldb.pb.ErrCode errcode = 1;
  bool has_errcode() const;
  private:
  bool _internal_has_errcode() const;
  public:
  void clear_errcode();
  ::baikaldb::pb::ErrCode errcode() const;
  void set_errcode(::baikaldb::pb::ErrCode value);
  private:
  ::baikaldb::pb::ErrCode _internal_errcode() const;
  void _internal_set_errcode(::baikaldb::pb::ErrCode value);
  public:

  // @@protoc_insertion_point(class_scope:baikaldb.pb.DbResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr errmsg_;
  int errcode_;
  friend struct ::TableStruct_db_2einterface_2eproto;
};
// -------------------------------------------------------------------

class DAGFragmentRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:baikaldb.pb.DAGFragmentRequest) */ {
 public:
  inline DAGFragmentRequest() : DAGFragmentRequest(nullptr) {}
  ~DAGFragmentRequest() override;
  explicit constexpr DAGFragmentRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DAGFragmentRequest(const DAGFragmentRequest& from);
  DAGFragmentRequest(DAGFragmentRequest&& from) noexcept
    : DAGFragmentRequest() {
    *this = ::std::move(from);
  }

  inline DAGFragmentRequest& operator=(const DAGFragmentRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline DAGFragmentRequest& operator=(DAGFragmentRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DAGFragmentRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const DAGFragmentRequest* internal_default_instance() {
    return reinterpret_cast<const DAGFragmentRequest*>(
               &_DAGFragmentRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(DAGFragmentRequest& a, DAGFragmentRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(DAGFragmentRequest* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DAGFragmentRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DAGFragmentRequest* New() const final {
    return new DAGFragmentRequest();
  }

  DAGFragmentRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DAGFragmentRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DAGFragmentRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const DAGFragmentRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DAGFragmentRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "baikaldb.pb.DAGFragmentRequest";
  }
  protected:
  explicit DAGFragmentRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFragmentsFieldNumber = 3,
    kUsernameFieldNumber = 5,
    kLogIdFieldNumber = 2,
    kSqlSignFieldNumber = 4,
    kOpFieldNumber = 1,
  };
  // repeated .baikaldb.pb.FragmentInfo fragments = 3;
  int fragments_size() const;
  private:
  int _internal_fragments_size() const;
  public:
  void clear_fragments();
  ::baikaldb::pb::FragmentInfo* mutable_fragments(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::baikaldb::pb::FragmentInfo >*
      mutable_fragments();
  private:
  const ::baikaldb::pb::FragmentInfo& _internal_fragments(int index) const;
  ::baikaldb::pb::FragmentInfo* _internal_add_fragments();
  public:
  const ::baikaldb::pb::FragmentInfo& fragments(int index) const;
  ::baikaldb::pb::FragmentInfo* add_fragments();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::baikaldb::pb::FragmentInfo >&
      fragments() const;

  // required string username = 5;
  bool has_username() const;
  private:
  bool _internal_has_username() const;
  public:
  void clear_username();
  const std::string& username() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_username(ArgT0&& arg0, ArgT... args);
  std::string* mutable_username();
  PROTOBUF_MUST_USE_RESULT std::string* release_username();
  void set_allocated_username(std::string* username);
  private:
  const std::string& _internal_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_username(const std::string& value);
  std::string* _internal_mutable_username();
  public:

  // required int64 log_id = 2;
  bool has_log_id() const;
  private:
  bool _internal_has_log_id() const;
  public:
  void clear_log_id();
  ::PROTOBUF_NAMESPACE_ID::int64 log_id() const;
  void set_log_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_log_id() const;
  void _internal_set_log_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // optional uint64 sql_sign = 4;
  bool has_sql_sign() const;
  private:
  bool _internal_has_sql_sign() const;
  public:
  void clear_sql_sign();
  ::PROTOBUF_NAMESPACE_ID::uint64 sql_sign() const;
  void set_sql_sign(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_sql_sign() const;
  void _internal_set_sql_sign(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // required .baikaldb.pb.FragmentOpType op = 1;
  bool has_op() const;
  private:
  bool _internal_has_op() const;
  public:
  void clear_op();
  ::baikaldb::pb::FragmentOpType op() const;
  void set_op(::baikaldb::pb::FragmentOpType value);
  private:
  ::baikaldb::pb::FragmentOpType _internal_op() const;
  void _internal_set_op(::baikaldb::pb::FragmentOpType value);
  public:

  // @@protoc_insertion_point(class_scope:baikaldb.pb.DAGFragmentRequest)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::baikaldb::pb::FragmentInfo > fragments_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr username_;
  ::PROTOBUF_NAMESPACE_ID::int64 log_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 sql_sign_;
  int op_;
  friend struct ::TableStruct_db_2einterface_2eproto;
};
// ===================================================================

class DbService_Stub;

class DbService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline DbService() {};
 public:
  virtual ~DbService();

  typedef DbService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void transmit_data(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::baikaldb::pb::TransmitDataParam* request,
                       ::baikaldb::pb::DbResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void handle_mpp_dag_fragment(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::baikaldb::pb::DAGFragmentRequest* request,
                       ::baikaldb::pb::DbResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(DbService);
};

class DbService_Stub : public DbService {
 public:
  DbService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  DbService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~DbService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements DbService ------------------------------------------

  void transmit_data(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::baikaldb::pb::TransmitDataParam* request,
                       ::baikaldb::pb::DbResponse* response,
                       ::google::protobuf::Closure* done);
  void handle_mpp_dag_fragment(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::baikaldb::pb::DAGFragmentRequest* request,
                       ::baikaldb::pb::DbResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(DbService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// QueryStat

// optional int64 num_affected_rows = 1;
inline bool QueryStat::_internal_has_num_affected_rows() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool QueryStat::has_num_affected_rows() const {
  return _internal_has_num_affected_rows();
}
inline void QueryStat::clear_num_affected_rows() {
  num_affected_rows_ = int64_t{0};
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 QueryStat::_internal_num_affected_rows() const {
  return num_affected_rows_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 QueryStat::num_affected_rows() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.QueryStat.num_affected_rows)
  return _internal_num_affected_rows();
}
inline void QueryStat::_internal_set_num_affected_rows(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  num_affected_rows_ = value;
}
inline void QueryStat::set_num_affected_rows(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_num_affected_rows(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.QueryStat.num_affected_rows)
}

// optional int64 num_returned_rows = 2;
inline bool QueryStat::_internal_has_num_returned_rows() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool QueryStat::has_num_returned_rows() const {
  return _internal_has_num_returned_rows();
}
inline void QueryStat::clear_num_returned_rows() {
  num_returned_rows_ = int64_t{0};
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 QueryStat::_internal_num_returned_rows() const {
  return num_returned_rows_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 QueryStat::num_returned_rows() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.QueryStat.num_returned_rows)
  return _internal_num_returned_rows();
}
inline void QueryStat::_internal_set_num_returned_rows(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000002u;
  num_returned_rows_ = value;
}
inline void QueryStat::set_num_returned_rows(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_num_returned_rows(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.QueryStat.num_returned_rows)
}

// optional int64 num_scan_rows = 3;
inline bool QueryStat::_internal_has_num_scan_rows() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool QueryStat::has_num_scan_rows() const {
  return _internal_has_num_scan_rows();
}
inline void QueryStat::clear_num_scan_rows() {
  num_scan_rows_ = int64_t{0};
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 QueryStat::_internal_num_scan_rows() const {
  return num_scan_rows_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 QueryStat::num_scan_rows() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.QueryStat.num_scan_rows)
  return _internal_num_scan_rows();
}
inline void QueryStat::_internal_set_num_scan_rows(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000004u;
  num_scan_rows_ = value;
}
inline void QueryStat::set_num_scan_rows(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_num_scan_rows(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.QueryStat.num_scan_rows)
}

// optional int64 num_filter_rows = 4;
inline bool QueryStat::_internal_has_num_filter_rows() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool QueryStat::has_num_filter_rows() const {
  return _internal_has_num_filter_rows();
}
inline void QueryStat::clear_num_filter_rows() {
  num_filter_rows_ = int64_t{0};
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 QueryStat::_internal_num_filter_rows() const {
  return num_filter_rows_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 QueryStat::num_filter_rows() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.QueryStat.num_filter_rows)
  return _internal_num_filter_rows();
}
inline void QueryStat::_internal_set_num_filter_rows(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000008u;
  num_filter_rows_ = value;
}
inline void QueryStat::set_num_filter_rows(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_num_filter_rows(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.QueryStat.num_filter_rows)
}

// optional int64 region_count = 5;
inline bool QueryStat::_internal_has_region_count() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool QueryStat::has_region_count() const {
  return _internal_has_region_count();
}
inline void QueryStat::clear_region_count() {
  region_count_ = int64_t{0};
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 QueryStat::_internal_region_count() const {
  return region_count_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 QueryStat::region_count() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.QueryStat.region_count)
  return _internal_region_count();
}
inline void QueryStat::_internal_set_region_count(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000010u;
  region_count_ = value;
}
inline void QueryStat::set_region_count(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_region_count(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.QueryStat.region_count)
}

// optional int64 db_handle_rows = 6;
inline bool QueryStat::_internal_has_db_handle_rows() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool QueryStat::has_db_handle_rows() const {
  return _internal_has_db_handle_rows();
}
inline void QueryStat::clear_db_handle_rows() {
  db_handle_rows_ = int64_t{0};
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 QueryStat::_internal_db_handle_rows() const {
  return db_handle_rows_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 QueryStat::db_handle_rows() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.QueryStat.db_handle_rows)
  return _internal_db_handle_rows();
}
inline void QueryStat::_internal_set_db_handle_rows(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000020u;
  db_handle_rows_ = value;
}
inline void QueryStat::set_db_handle_rows(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_db_handle_rows(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.QueryStat.db_handle_rows)
}

// optional int64 db_handle_bytes = 7;
inline bool QueryStat::_internal_has_db_handle_bytes() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool QueryStat::has_db_handle_bytes() const {
  return _internal_has_db_handle_bytes();
}
inline void QueryStat::clear_db_handle_bytes() {
  db_handle_bytes_ = int64_t{0};
  _has_bits_[0] &= ~0x00000040u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 QueryStat::_internal_db_handle_bytes() const {
  return db_handle_bytes_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 QueryStat::db_handle_bytes() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.QueryStat.db_handle_bytes)
  return _internal_db_handle_bytes();
}
inline void QueryStat::_internal_set_db_handle_bytes(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000040u;
  db_handle_bytes_ = value;
}
inline void QueryStat::set_db_handle_bytes(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_db_handle_bytes(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.QueryStat.db_handle_bytes)
}

// -------------------------------------------------------------------

// TransmitDataParam

// required .baikaldb.pb.ExchangeState exchange_state = 1;
inline bool TransmitDataParam::_internal_has_exchange_state() const {
  bool value = (_has_bits_[0] & 0x00001000u) != 0;
  return value;
}
inline bool TransmitDataParam::has_exchange_state() const {
  return _internal_has_exchange_state();
}
inline void TransmitDataParam::clear_exchange_state() {
  exchange_state_ = 1;
  _has_bits_[0] &= ~0x00001000u;
}
inline ::baikaldb::pb::ExchangeState TransmitDataParam::_internal_exchange_state() const {
  return static_cast< ::baikaldb::pb::ExchangeState >(exchange_state_);
}
inline ::baikaldb::pb::ExchangeState TransmitDataParam::exchange_state() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.TransmitDataParam.exchange_state)
  return _internal_exchange_state();
}
inline void TransmitDataParam::_internal_set_exchange_state(::baikaldb::pb::ExchangeState value) {
  assert(::baikaldb::pb::ExchangeState_IsValid(value));
  _has_bits_[0] |= 0x00001000u;
  exchange_state_ = value;
}
inline void TransmitDataParam::set_exchange_state(::baikaldb::pb::ExchangeState value) {
  _internal_set_exchange_state(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.TransmitDataParam.exchange_state)
}

// required uint64 log_id = 2;
inline bool TransmitDataParam::_internal_has_log_id() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool TransmitDataParam::has_log_id() const {
  return _internal_has_log_id();
}
inline void TransmitDataParam::clear_log_id() {
  log_id_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 TransmitDataParam::_internal_log_id() const {
  return log_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 TransmitDataParam::log_id() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.TransmitDataParam.log_id)
  return _internal_log_id();
}
inline void TransmitDataParam::_internal_set_log_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000004u;
  log_id_ = value;
}
inline void TransmitDataParam::set_log_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_log_id(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.TransmitDataParam.log_id)
}

// required uint64 sender_fragment_instance_id = 3;
inline bool TransmitDataParam::_internal_has_sender_fragment_instance_id() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool TransmitDataParam::has_sender_fragment_instance_id() const {
  return _internal_has_sender_fragment_instance_id();
}
inline void TransmitDataParam::clear_sender_fragment_instance_id() {
  sender_fragment_instance_id_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 TransmitDataParam::_internal_sender_fragment_instance_id() const {
  return sender_fragment_instance_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 TransmitDataParam::sender_fragment_instance_id() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.TransmitDataParam.sender_fragment_instance_id)
  return _internal_sender_fragment_instance_id();
}
inline void TransmitDataParam::_internal_set_sender_fragment_instance_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000008u;
  sender_fragment_instance_id_ = value;
}
inline void TransmitDataParam::set_sender_fragment_instance_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_sender_fragment_instance_id(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.TransmitDataParam.sender_fragment_instance_id)
}

// required uint64 receiver_fragment_instance_id = 4;
inline bool TransmitDataParam::_internal_has_receiver_fragment_instance_id() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool TransmitDataParam::has_receiver_fragment_instance_id() const {
  return _internal_has_receiver_fragment_instance_id();
}
inline void TransmitDataParam::clear_receiver_fragment_instance_id() {
  receiver_fragment_instance_id_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 TransmitDataParam::_internal_receiver_fragment_instance_id() const {
  return receiver_fragment_instance_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 TransmitDataParam::receiver_fragment_instance_id() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.TransmitDataParam.receiver_fragment_instance_id)
  return _internal_receiver_fragment_instance_id();
}
inline void TransmitDataParam::_internal_set_receiver_fragment_instance_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000010u;
  receiver_fragment_instance_id_ = value;
}
inline void TransmitDataParam::set_receiver_fragment_instance_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_receiver_fragment_instance_id(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.TransmitDataParam.receiver_fragment_instance_id)
}

// required int32 receiver_node_id = 5;
inline bool TransmitDataParam::_internal_has_receiver_node_id() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool TransmitDataParam::has_receiver_node_id() const {
  return _internal_has_receiver_node_id();
}
inline void TransmitDataParam::clear_receiver_node_id() {
  receiver_node_id_ = 0;
  _has_bits_[0] &= ~0x00000080u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TransmitDataParam::_internal_receiver_node_id() const {
  return receiver_node_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TransmitDataParam::receiver_node_id() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.TransmitDataParam.receiver_node_id)
  return _internal_receiver_node_id();
}
inline void TransmitDataParam::_internal_set_receiver_node_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000080u;
  receiver_node_id_ = value;
}
inline void TransmitDataParam::set_receiver_node_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_receiver_node_id(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.TransmitDataParam.receiver_node_id)
}

// optional int64 region_id = 6;
inline bool TransmitDataParam::_internal_has_region_id() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool TransmitDataParam::has_region_id() const {
  return _internal_has_region_id();
}
inline void TransmitDataParam::clear_region_id() {
  region_id_ = int64_t{0};
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TransmitDataParam::_internal_region_id() const {
  return region_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TransmitDataParam::region_id() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.TransmitDataParam.region_id)
  return _internal_region_id();
}
inline void TransmitDataParam::_internal_set_region_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000020u;
  region_id_ = value;
}
inline void TransmitDataParam::set_region_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_region_id(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.TransmitDataParam.region_id)
}

// optional int64 region_version = 7;
inline bool TransmitDataParam::_internal_has_region_version() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool TransmitDataParam::has_region_version() const {
  return _internal_has_region_version();
}
inline void TransmitDataParam::clear_region_version() {
  region_version_ = int64_t{0};
  _has_bits_[0] &= ~0x00000040u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TransmitDataParam::_internal_region_version() const {
  return region_version_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TransmitDataParam::region_version() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.TransmitDataParam.region_version)
  return _internal_region_version();
}
inline void TransmitDataParam::_internal_set_region_version(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000040u;
  region_version_ = value;
}
inline void TransmitDataParam::set_region_version(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_region_version(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.TransmitDataParam.region_version)
}

// optional bool is_merge = 8;
inline bool TransmitDataParam::_internal_has_is_merge() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool TransmitDataParam::has_is_merge() const {
  return _internal_has_is_merge();
}
inline void TransmitDataParam::clear_is_merge() {
  is_merge_ = false;
  _has_bits_[0] &= ~0x00000100u;
}
inline bool TransmitDataParam::_internal_is_merge() const {
  return is_merge_;
}
inline bool TransmitDataParam::is_merge() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.TransmitDataParam.is_merge)
  return _internal_is_merge();
}
inline void TransmitDataParam::_internal_set_is_merge(bool value) {
  _has_bits_[0] |= 0x00000100u;
  is_merge_ = value;
}
inline void TransmitDataParam::set_is_merge(bool value) {
  _internal_set_is_merge(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.TransmitDataParam.is_merge)
}

// repeated .baikaldb.pb.RegionInfo region_infos = 9;
inline int TransmitDataParam::_internal_region_infos_size() const {
  return region_infos_.size();
}
inline int TransmitDataParam::region_infos_size() const {
  return _internal_region_infos_size();
}
inline ::baikaldb::pb::RegionInfo* TransmitDataParam::mutable_region_infos(int index) {
  // @@protoc_insertion_point(field_mutable:baikaldb.pb.TransmitDataParam.region_infos)
  return region_infos_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::baikaldb::pb::RegionInfo >*
TransmitDataParam::mutable_region_infos() {
  // @@protoc_insertion_point(field_mutable_list:baikaldb.pb.TransmitDataParam.region_infos)
  return &region_infos_;
}
inline const ::baikaldb::pb::RegionInfo& TransmitDataParam::_internal_region_infos(int index) const {
  return region_infos_.Get(index);
}
inline const ::baikaldb::pb::RegionInfo& TransmitDataParam::region_infos(int index) const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.TransmitDataParam.region_infos)
  return _internal_region_infos(index);
}
inline ::baikaldb::pb::RegionInfo* TransmitDataParam::_internal_add_region_infos() {
  return region_infos_.Add();
}
inline ::baikaldb::pb::RegionInfo* TransmitDataParam::add_region_infos() {
  ::baikaldb::pb::RegionInfo* _add = _internal_add_region_infos();
  // @@protoc_insertion_point(field_add:baikaldb.pb.TransmitDataParam.region_infos)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::baikaldb::pb::RegionInfo >&
TransmitDataParam::region_infos() const {
  // @@protoc_insertion_point(field_list:baikaldb.pb.TransmitDataParam.region_infos)
  return region_infos_;
}

// optional int64 record_batch_seq = 10;
inline bool TransmitDataParam::_internal_has_record_batch_seq() const {
  bool value = (_has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline bool TransmitDataParam::has_record_batch_seq() const {
  return _internal_has_record_batch_seq();
}
inline void TransmitDataParam::clear_record_batch_seq() {
  record_batch_seq_ = int64_t{0};
  _has_bits_[0] &= ~0x00000400u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TransmitDataParam::_internal_record_batch_seq() const {
  return record_batch_seq_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TransmitDataParam::record_batch_seq() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.TransmitDataParam.record_batch_seq)
  return _internal_record_batch_seq();
}
inline void TransmitDataParam::_internal_set_record_batch_seq(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000400u;
  record_batch_seq_ = value;
}
inline void TransmitDataParam::set_record_batch_seq(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_record_batch_seq(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.TransmitDataParam.record_batch_seq)
}

// optional .baikaldb.pb.QueryStat query_stat = 11;
inline bool TransmitDataParam::_internal_has_query_stat() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || query_stat_ != nullptr);
  return value;
}
inline bool TransmitDataParam::has_query_stat() const {
  return _internal_has_query_stat();
}
inline void TransmitDataParam::clear_query_stat() {
  if (query_stat_ != nullptr) query_stat_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::baikaldb::pb::QueryStat& TransmitDataParam::_internal_query_stat() const {
  const ::baikaldb::pb::QueryStat* p = query_stat_;
  return p != nullptr ? *p : reinterpret_cast<const ::baikaldb::pb::QueryStat&>(
      ::baikaldb::pb::_QueryStat_default_instance_);
}
inline const ::baikaldb::pb::QueryStat& TransmitDataParam::query_stat() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.TransmitDataParam.query_stat)
  return _internal_query_stat();
}
inline void TransmitDataParam::unsafe_arena_set_allocated_query_stat(
    ::baikaldb::pb::QueryStat* query_stat) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(query_stat_);
  }
  query_stat_ = query_stat;
  if (query_stat) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:baikaldb.pb.TransmitDataParam.query_stat)
}
inline ::baikaldb::pb::QueryStat* TransmitDataParam::release_query_stat() {
  _has_bits_[0] &= ~0x00000002u;
  ::baikaldb::pb::QueryStat* temp = query_stat_;
  query_stat_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::baikaldb::pb::QueryStat* TransmitDataParam::unsafe_arena_release_query_stat() {
  // @@protoc_insertion_point(field_release:baikaldb.pb.TransmitDataParam.query_stat)
  _has_bits_[0] &= ~0x00000002u;
  ::baikaldb::pb::QueryStat* temp = query_stat_;
  query_stat_ = nullptr;
  return temp;
}
inline ::baikaldb::pb::QueryStat* TransmitDataParam::_internal_mutable_query_stat() {
  _has_bits_[0] |= 0x00000002u;
  if (query_stat_ == nullptr) {
    auto* p = CreateMaybeMessage<::baikaldb::pb::QueryStat>(GetArenaForAllocation());
    query_stat_ = p;
  }
  return query_stat_;
}
inline ::baikaldb::pb::QueryStat* TransmitDataParam::mutable_query_stat() {
  ::baikaldb::pb::QueryStat* _msg = _internal_mutable_query_stat();
  // @@protoc_insertion_point(field_mutable:baikaldb.pb.TransmitDataParam.query_stat)
  return _msg;
}
inline void TransmitDataParam::set_allocated_query_stat(::baikaldb::pb::QueryStat* query_stat) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete query_stat_;
  }
  if (query_stat) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::baikaldb::pb::QueryStat>::GetOwningArena(query_stat);
    if (message_arena != submessage_arena) {
      query_stat = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, query_stat, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  query_stat_ = query_stat;
  // @@protoc_insertion_point(field_set_allocated:baikaldb.pb.TransmitDataParam.query_stat)
}

// optional bytes vectorized_schema = 12;
inline bool TransmitDataParam::_internal_has_vectorized_schema() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool TransmitDataParam::has_vectorized_schema() const {
  return _internal_has_vectorized_schema();
}
inline void TransmitDataParam::clear_vectorized_schema() {
  vectorized_schema_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& TransmitDataParam::vectorized_schema() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.TransmitDataParam.vectorized_schema)
  return _internal_vectorized_schema();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TransmitDataParam::set_vectorized_schema(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 vectorized_schema_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:baikaldb.pb.TransmitDataParam.vectorized_schema)
}
inline std::string* TransmitDataParam::mutable_vectorized_schema() {
  std::string* _s = _internal_mutable_vectorized_schema();
  // @@protoc_insertion_point(field_mutable:baikaldb.pb.TransmitDataParam.vectorized_schema)
  return _s;
}
inline const std::string& TransmitDataParam::_internal_vectorized_schema() const {
  return vectorized_schema_.Get();
}
inline void TransmitDataParam::_internal_set_vectorized_schema(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  vectorized_schema_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* TransmitDataParam::_internal_mutable_vectorized_schema() {
  _has_bits_[0] |= 0x00000001u;
  return vectorized_schema_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* TransmitDataParam::release_vectorized_schema() {
  // @@protoc_insertion_point(field_release:baikaldb.pb.TransmitDataParam.vectorized_schema)
  if (!_internal_has_vectorized_schema()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return vectorized_schema_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void TransmitDataParam::set_allocated_vectorized_schema(std::string* vectorized_schema) {
  if (vectorized_schema != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  vectorized_schema_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), vectorized_schema,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:baikaldb.pb.TransmitDataParam.vectorized_schema)
}

// required bool is_local_pass_through = 13;
inline bool TransmitDataParam::_internal_has_is_local_pass_through() const {
  bool value = (_has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool TransmitDataParam::has_is_local_pass_through() const {
  return _internal_has_is_local_pass_through();
}
inline void TransmitDataParam::clear_is_local_pass_through() {
  is_local_pass_through_ = false;
  _has_bits_[0] &= ~0x00000200u;
}
inline bool TransmitDataParam::_internal_is_local_pass_through() const {
  return is_local_pass_through_;
}
inline bool TransmitDataParam::is_local_pass_through() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.TransmitDataParam.is_local_pass_through)
  return _internal_is_local_pass_through();
}
inline void TransmitDataParam::_internal_set_is_local_pass_through(bool value) {
  _has_bits_[0] |= 0x00000200u;
  is_local_pass_through_ = value;
}
inline void TransmitDataParam::set_is_local_pass_through(bool value) {
  _internal_set_is_local_pass_through(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.TransmitDataParam.is_local_pass_through)
}

// optional int64 record_batch_rows = 14;
inline bool TransmitDataParam::_internal_has_record_batch_rows() const {
  bool value = (_has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline bool TransmitDataParam::has_record_batch_rows() const {
  return _internal_has_record_batch_rows();
}
inline void TransmitDataParam::clear_record_batch_rows() {
  record_batch_rows_ = int64_t{0};
  _has_bits_[0] &= ~0x00000800u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TransmitDataParam::_internal_record_batch_rows() const {
  return record_batch_rows_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TransmitDataParam::record_batch_rows() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.TransmitDataParam.record_batch_rows)
  return _internal_record_batch_rows();
}
inline void TransmitDataParam::_internal_set_record_batch_rows(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000800u;
  record_batch_rows_ = value;
}
inline void TransmitDataParam::set_record_batch_rows(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_record_batch_rows(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.TransmitDataParam.record_batch_rows)
}

// -------------------------------------------------------------------

// DbResponse

// required .baikaldb.pb.ErrCode errcode = 1;
inline bool DbResponse::_internal_has_errcode() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool DbResponse::has_errcode() const {
  return _internal_has_errcode();
}
inline void DbResponse::clear_errcode() {
  errcode_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::baikaldb::pb::ErrCode DbResponse::_internal_errcode() const {
  return static_cast< ::baikaldb::pb::ErrCode >(errcode_);
}
inline ::baikaldb::pb::ErrCode DbResponse::errcode() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.DbResponse.errcode)
  return _internal_errcode();
}
inline void DbResponse::_internal_set_errcode(::baikaldb::pb::ErrCode value) {
  assert(::baikaldb::pb::ErrCode_IsValid(value));
  _has_bits_[0] |= 0x00000002u;
  errcode_ = value;
}
inline void DbResponse::set_errcode(::baikaldb::pb::ErrCode value) {
  _internal_set_errcode(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.DbResponse.errcode)
}

// optional string errmsg = 2;
inline bool DbResponse::_internal_has_errmsg() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool DbResponse::has_errmsg() const {
  return _internal_has_errmsg();
}
inline void DbResponse::clear_errmsg() {
  errmsg_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& DbResponse::errmsg() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.DbResponse.errmsg)
  return _internal_errmsg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DbResponse::set_errmsg(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 errmsg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:baikaldb.pb.DbResponse.errmsg)
}
inline std::string* DbResponse::mutable_errmsg() {
  std::string* _s = _internal_mutable_errmsg();
  // @@protoc_insertion_point(field_mutable:baikaldb.pb.DbResponse.errmsg)
  return _s;
}
inline const std::string& DbResponse::_internal_errmsg() const {
  return errmsg_.Get();
}
inline void DbResponse::_internal_set_errmsg(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  errmsg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DbResponse::_internal_mutable_errmsg() {
  _has_bits_[0] |= 0x00000001u;
  return errmsg_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DbResponse::release_errmsg() {
  // @@protoc_insertion_point(field_release:baikaldb.pb.DbResponse.errmsg)
  if (!_internal_has_errmsg()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return errmsg_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DbResponse::set_allocated_errmsg(std::string* errmsg) {
  if (errmsg != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  errmsg_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), errmsg,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:baikaldb.pb.DbResponse.errmsg)
}

// -------------------------------------------------------------------

// DAGFragmentRequest

// required .baikaldb.pb.FragmentOpType op = 1;
inline bool DAGFragmentRequest::_internal_has_op() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool DAGFragmentRequest::has_op() const {
  return _internal_has_op();
}
inline void DAGFragmentRequest::clear_op() {
  op_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::baikaldb::pb::FragmentOpType DAGFragmentRequest::_internal_op() const {
  return static_cast< ::baikaldb::pb::FragmentOpType >(op_);
}
inline ::baikaldb::pb::FragmentOpType DAGFragmentRequest::op() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.DAGFragmentRequest.op)
  return _internal_op();
}
inline void DAGFragmentRequest::_internal_set_op(::baikaldb::pb::FragmentOpType value) {
  assert(::baikaldb::pb::FragmentOpType_IsValid(value));
  _has_bits_[0] |= 0x00000008u;
  op_ = value;
}
inline void DAGFragmentRequest::set_op(::baikaldb::pb::FragmentOpType value) {
  _internal_set_op(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.DAGFragmentRequest.op)
}

// required int64 log_id = 2;
inline bool DAGFragmentRequest::_internal_has_log_id() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool DAGFragmentRequest::has_log_id() const {
  return _internal_has_log_id();
}
inline void DAGFragmentRequest::clear_log_id() {
  log_id_ = int64_t{0};
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 DAGFragmentRequest::_internal_log_id() const {
  return log_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 DAGFragmentRequest::log_id() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.DAGFragmentRequest.log_id)
  return _internal_log_id();
}
inline void DAGFragmentRequest::_internal_set_log_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000002u;
  log_id_ = value;
}
inline void DAGFragmentRequest::set_log_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_log_id(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.DAGFragmentRequest.log_id)
}

// repeated .baikaldb.pb.FragmentInfo fragments = 3;
inline int DAGFragmentRequest::_internal_fragments_size() const {
  return fragments_.size();
}
inline int DAGFragmentRequest::fragments_size() const {
  return _internal_fragments_size();
}
inline ::baikaldb::pb::FragmentInfo* DAGFragmentRequest::mutable_fragments(int index) {
  // @@protoc_insertion_point(field_mutable:baikaldb.pb.DAGFragmentRequest.fragments)
  return fragments_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::baikaldb::pb::FragmentInfo >*
DAGFragmentRequest::mutable_fragments() {
  // @@protoc_insertion_point(field_mutable_list:baikaldb.pb.DAGFragmentRequest.fragments)
  return &fragments_;
}
inline const ::baikaldb::pb::FragmentInfo& DAGFragmentRequest::_internal_fragments(int index) const {
  return fragments_.Get(index);
}
inline const ::baikaldb::pb::FragmentInfo& DAGFragmentRequest::fragments(int index) const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.DAGFragmentRequest.fragments)
  return _internal_fragments(index);
}
inline ::baikaldb::pb::FragmentInfo* DAGFragmentRequest::_internal_add_fragments() {
  return fragments_.Add();
}
inline ::baikaldb::pb::FragmentInfo* DAGFragmentRequest::add_fragments() {
  ::baikaldb::pb::FragmentInfo* _add = _internal_add_fragments();
  // @@protoc_insertion_point(field_add:baikaldb.pb.DAGFragmentRequest.fragments)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::baikaldb::pb::FragmentInfo >&
DAGFragmentRequest::fragments() const {
  // @@protoc_insertion_point(field_list:baikaldb.pb.DAGFragmentRequest.fragments)
  return fragments_;
}

// optional uint64 sql_sign = 4;
inline bool DAGFragmentRequest::_internal_has_sql_sign() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool DAGFragmentRequest::has_sql_sign() const {
  return _internal_has_sql_sign();
}
inline void DAGFragmentRequest::clear_sql_sign() {
  sql_sign_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 DAGFragmentRequest::_internal_sql_sign() const {
  return sql_sign_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 DAGFragmentRequest::sql_sign() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.DAGFragmentRequest.sql_sign)
  return _internal_sql_sign();
}
inline void DAGFragmentRequest::_internal_set_sql_sign(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000004u;
  sql_sign_ = value;
}
inline void DAGFragmentRequest::set_sql_sign(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_sql_sign(value);
  // @@protoc_insertion_point(field_set:baikaldb.pb.DAGFragmentRequest.sql_sign)
}

// required string username = 5;
inline bool DAGFragmentRequest::_internal_has_username() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool DAGFragmentRequest::has_username() const {
  return _internal_has_username();
}
inline void DAGFragmentRequest::clear_username() {
  username_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& DAGFragmentRequest::username() const {
  // @@protoc_insertion_point(field_get:baikaldb.pb.DAGFragmentRequest.username)
  return _internal_username();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DAGFragmentRequest::set_username(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 username_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:baikaldb.pb.DAGFragmentRequest.username)
}
inline std::string* DAGFragmentRequest::mutable_username() {
  std::string* _s = _internal_mutable_username();
  // @@protoc_insertion_point(field_mutable:baikaldb.pb.DAGFragmentRequest.username)
  return _s;
}
inline const std::string& DAGFragmentRequest::_internal_username() const {
  return username_.Get();
}
inline void DAGFragmentRequest::_internal_set_username(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  username_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DAGFragmentRequest::_internal_mutable_username() {
  _has_bits_[0] |= 0x00000001u;
  return username_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DAGFragmentRequest::release_username() {
  // @@protoc_insertion_point(field_release:baikaldb.pb.DAGFragmentRequest.username)
  if (!_internal_has_username()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return username_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DAGFragmentRequest::set_allocated_username(std::string* username) {
  if (username != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  username_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), username,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:baikaldb.pb.DAGFragmentRequest.username)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace baikaldb

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::baikaldb::pb::ExchangeState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::baikaldb::pb::ExchangeState>() {
  return ::baikaldb::pb::ExchangeState_descriptor();
}
template <> struct is_proto_enum< ::baikaldb::pb::FragmentOpType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::baikaldb::pb::FragmentOpType>() {
  return ::baikaldb::pb::FragmentOpType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_db_2einterface_2eproto
