// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: expr.proto

#include "expr.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace baikaldb {
namespace pb {
constexpr Function::Function(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : arg_types_()
  , name_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , fn_op_(0)
  , return_type_(0)

  , has_var_args_(false){}
struct FunctionDefaultTypeInternal {
  constexpr FunctionDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~FunctionDefaultTypeInternal() {}
  union {
    Function _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT FunctionDefaultTypeInternal _Function_default_instance_;
constexpr DeriveExprNode::DeriveExprNode(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : string_val_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , field_name_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , tuple_id_(0)
  , slot_id_(0)
  , int_val_(int64_t{0})
  , double_val_(0)
  , bool_val_(false)
  , intermediate_slot_id_(0)
  , field_id_(0)
  , placeholder_id_(0){}
struct DeriveExprNodeDefaultTypeInternal {
  constexpr DeriveExprNodeDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~DeriveExprNodeDefaultTypeInternal() {}
  union {
    DeriveExprNode _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT DeriveExprNodeDefaultTypeInternal _DeriveExprNode_default_instance_;
constexpr ExprNode::ExprNode(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : fn_(nullptr)
  , derive_node_(nullptr)
  , col_type_(0)

  , num_children_(0)
  , col_flag_(0u)
  , charset_(0)

  , node_type_(1)
{}
struct ExprNodeDefaultTypeInternal {
  constexpr ExprNodeDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ExprNodeDefaultTypeInternal() {}
  union {
    ExprNode _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ExprNodeDefaultTypeInternal _ExprNode_default_instance_;
constexpr Expr::Expr(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : nodes_()
  , index_ids_()
  , database_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , table_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct ExprDefaultTypeInternal {
  constexpr ExprDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ExprDefaultTypeInternal() {}
  union {
    Expr _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ExprDefaultTypeInternal _Expr_default_instance_;
constexpr Exprs::Exprs(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : exprs_(){}
struct ExprsDefaultTypeInternal {
  constexpr ExprsDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ExprsDefaultTypeInternal() {}
  union {
    Exprs _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ExprsDefaultTypeInternal _Exprs_default_instance_;
constexpr ColumnDdlInfo::ColumnDdlInfo(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : update_exprs_()
  , update_slots_()
  , scan_conjuncts_()
  , tuples_()
  , opt_sql_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct ColumnDdlInfoDefaultTypeInternal {
  constexpr ColumnDdlInfoDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ColumnDdlInfoDefaultTypeInternal() {}
  union {
    ColumnDdlInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ColumnDdlInfoDefaultTypeInternal _ColumnDdlInfo_default_instance_;
}  // namespace pb
}  // namespace baikaldb
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_expr_2eproto[6];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_expr_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_expr_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_expr_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::Function, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::Function, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::Function, name_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::Function, fn_op_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::Function, arg_types_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::Function, return_type_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::Function, has_var_args_),
  0,
  1,
  ~0u,
  2,
  3,
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::DeriveExprNode, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::DeriveExprNode, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::DeriveExprNode, tuple_id_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::DeriveExprNode, slot_id_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::DeriveExprNode, int_val_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::DeriveExprNode, double_val_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::DeriveExprNode, string_val_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::DeriveExprNode, bool_val_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::DeriveExprNode, intermediate_slot_id_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::DeriveExprNode, field_id_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::DeriveExprNode, field_name_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::DeriveExprNode, placeholder_id_),
  2,
  3,
  4,
  5,
  0,
  6,
  7,
  8,
  1,
  9,
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::ExprNode, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::ExprNode, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::ExprNode, node_type_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::ExprNode, col_type_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::ExprNode, num_children_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::ExprNode, fn_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::ExprNode, derive_node_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::ExprNode, col_flag_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::ExprNode, charset_),
  6,
  2,
  3,
  0,
  1,
  4,
  5,
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::Expr, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::Expr, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::Expr, nodes_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::Expr, index_ids_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::Expr, database_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::Expr, table_),
  ~0u,
  ~0u,
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::Exprs, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::Exprs, exprs_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::ColumnDdlInfo, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::ColumnDdlInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::ColumnDdlInfo, update_exprs_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::ColumnDdlInfo, update_slots_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::ColumnDdlInfo, scan_conjuncts_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::ColumnDdlInfo, tuples_),
  PROTOBUF_FIELD_OFFSET(::baikaldb::pb::ColumnDdlInfo, opt_sql_),
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  0,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 11, -1, sizeof(::baikaldb::pb::Function)},
  { 16, 32, -1, sizeof(::baikaldb::pb::DeriveExprNode)},
  { 42, 55, -1, sizeof(::baikaldb::pb::ExprNode)},
  { 62, 72, -1, sizeof(::baikaldb::pb::Expr)},
  { 76, -1, -1, sizeof(::baikaldb::pb::Exprs)},
  { 83, 94, -1, sizeof(::baikaldb::pb::ColumnDdlInfo)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::baikaldb::pb::_Function_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::baikaldb::pb::_DeriveExprNode_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::baikaldb::pb::_ExprNode_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::baikaldb::pb::_Expr_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::baikaldb::pb::_Exprs_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::baikaldb::pb::_ColumnDdlInfo_default_instance_),
};

const char descriptor_table_protodef_expr_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nexpr.proto\022\013baikaldb.pb\032\014common.proto\""
  "\235\001\n\010Function\022\014\n\004name\030\001 \002(\t\022\r\n\005fn_op\030\002 \002("
  "\005\022-\n\targ_types\030\003 \003(\0162\032.baikaldb.pb.Primi"
  "tiveType\022/\n\013return_type\030\004 \001(\0162\032.baikaldb"
  ".pb.PrimitiveType\022\024\n\014has_var_args\030\005 \001(\010\""
  "\332\001\n\016DeriveExprNode\022\020\n\010tuple_id\030\001 \001(\005\022\017\n\007"
  "slot_id\030\002 \001(\005\022\017\n\007int_val\030\003 \001(\003\022\022\n\ndouble"
  "_val\030\004 \001(\001\022\022\n\nstring_val\030\005 \001(\014\022\020\n\010bool_v"
  "al\030\006 \001(\010\022\034\n\024intermediate_slot_id\030\007 \001(\005\022\020"
  "\n\010field_id\030\010 \001(\005\022\022\n\nfield_name\030\t \001(\t\022\026\n\016"
  "placeholder_id\030\n \001(\005\"\212\002\n\010ExprNode\022,\n\tnod"
  "e_type\030\001 \002(\0162\031.baikaldb.pb.ExprNodeType\022"
  ",\n\010col_type\030\002 \002(\0162\032.baikaldb.pb.Primitiv"
  "eType\022\024\n\014num_children\030\003 \002(\005\022!\n\002fn\030\004 \001(\0132"
  "\025.baikaldb.pb.Function\0220\n\013derive_node\030\005 "
  "\001(\0132\033.baikaldb.pb.DeriveExprNode\022\020\n\010col_"
  "flag\030\006 \001(\r\022%\n\007charset\030\007 \001(\0162\024.baikaldb.p"
  "b.Charset\"`\n\004Expr\022$\n\005nodes\030\001 \003(\0132\025.baika"
  "ldb.pb.ExprNode\022\021\n\tindex_ids\030\002 \003(\003\022\020\n\010da"
  "tabase\030\003 \001(\t\022\r\n\005table\030\004 \001(\t\")\n\005Exprs\022 \n\005"
  "exprs\030\001 \003(\0132\021.baikaldb.pb.Expr\"\325\001\n\rColum"
  "nDdlInfo\022\'\n\014update_exprs\030\001 \003(\0132\021.baikald"
  "b.pb.Expr\0221\n\014update_slots\030\002 \003(\0132\033.baikal"
  "db.pb.SlotDescriptor\022)\n\016scan_conjuncts\030\003"
  " \003(\0132\021.baikaldb.pb.Expr\022,\n\006tuples\030\004 \003(\0132"
  "\034.baikaldb.pb.TupleDescriptor\022\017\n\007opt_sql"
  "\030\005 \001(\t*\316\004\n\014ExprNodeType\022\014\n\010SLOT_REF\020\001\022\021\n"
  "\rFUNCTION_CALL\020\002\022\014\n\010AGG_EXPR\020\003\022\020\n\014NULL_L"
  "ITERAL\020\004\022\020\n\014BOOL_LITERAL\020\005\022\017\n\013INT_LITERA"
  "L\020\006\022\022\n\016DOUBLE_LITERAL\020\007\022\022\n\016STRING_LITERA"
  "L\020\010\022\025\n\021IS_NULL_PREDICATE\020\t\022\020\n\014IN_PREDICA"
  "TE\020\n\022\022\n\016LIKE_PREDICATE\020\013\022\021\n\rNOT_PREDICAT"
  "E\020\014\022\021\n\rAND_PREDICATE\020\r\022\020\n\014OR_PREDICATE\020\016"
  "\022\021\n\rXOR_PREDICATE\020\017\022\025\n\021TIMESTAMP_LITERAL"
  "\020\020\022\024\n\020DATETIME_LITERAL\020\021\022\020\n\014DATE_LITERAL"
  "\020\022\022\025\n\021IS_TRUE_PREDICATE\020\023\022\020\n\014TIME_LITERA"
  "L\020\024\022\030\n\024PLACE_HOLDER_LITERAL\020\025\022\014\n\010ROW_EXP"
  "R\020\026\022\017\n\013HLL_LITERAL\020\027\022\017\n\013HEX_LITERAL\020\030\022\022\n"
  "\016SUB_QUERY_EXPR\020\031\022\022\n\016BITMAP_LITERAL\020\032\022\023\n"
  "\017TDIGEST_LITERAL\020\033\022\024\n\020REGEXP_PREDICATE\020\034"
  "\022\024\n\020MAXVALUE_LITERAL\020\035\022\017\n\013WINDOW_EXPR\020\036"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_expr_2eproto_deps[1] = {
  &::descriptor_table_common_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_expr_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_expr_2eproto = {
  false, false, 1639, descriptor_table_protodef_expr_2eproto, "expr.proto", 
  &descriptor_table_expr_2eproto_once, descriptor_table_expr_2eproto_deps, 1, 6,
  schemas, file_default_instances, TableStruct_expr_2eproto::offsets,
  file_level_metadata_expr_2eproto, file_level_enum_descriptors_expr_2eproto, file_level_service_descriptors_expr_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_expr_2eproto_getter() {
  return &descriptor_table_expr_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_expr_2eproto(&descriptor_table_expr_2eproto);
namespace baikaldb {
namespace pb {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ExprNodeType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_expr_2eproto);
  return file_level_enum_descriptors_expr_2eproto[0];
}
bool ExprNodeType_IsValid(int value) {
  switch (value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 28:
    case 29:
    case 30:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class Function::_Internal {
 public:
  using HasBits = decltype(std::declval<Function>()._has_bits_);
  static void set_has_name(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_fn_op(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_return_type(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_has_var_args(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000003) ^ 0x00000003) != 0;
  }
};

Function::Function(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  arg_types_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:baikaldb.pb.Function)
}
Function::Function(const Function& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_),
      arg_types_(from.arg_types_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_name()) {
    name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_name(), 
      GetArenaForAllocation());
  }
  ::memcpy(&fn_op_, &from.fn_op_,
    static_cast<size_t>(reinterpret_cast<char*>(&has_var_args_) -
    reinterpret_cast<char*>(&fn_op_)) + sizeof(has_var_args_));
  // @@protoc_insertion_point(copy_constructor:baikaldb.pb.Function)
}

void Function::SharedCtor() {
name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&fn_op_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&has_var_args_) -
    reinterpret_cast<char*>(&fn_op_)) + sizeof(has_var_args_));
}

Function::~Function() {
  // @@protoc_insertion_point(destructor:baikaldb.pb.Function)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Function::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void Function::ArenaDtor(void* object) {
  Function* _this = reinterpret_cast< Function* >(object);
  (void)_this;
}
void Function::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Function::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Function::Clear() {
// @@protoc_insertion_point(message_clear_start:baikaldb.pb.Function)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  arg_types_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    name_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x0000000eu) {
    ::memset(&fn_op_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&has_var_args_) -
        reinterpret_cast<char*>(&fn_op_)) + sizeof(has_var_args_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Function::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "baikaldb.pb.Function.name");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // required int32 fn_op = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _Internal::set_has_fn_op(&has_bits);
          fn_op_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .baikaldb.pb.PrimitiveType arg_types = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          ptr -= 1;
          do {
            ptr += 1;
            ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
            CHK_(ptr);
            if (PROTOBUF_PREDICT_TRUE(::baikaldb::pb::PrimitiveType_IsValid(val))) {
              _internal_add_arg_types(static_cast<::baikaldb::pb::PrimitiveType>(val));
            } else {
              ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(3, val, mutable_unknown_fields());
            }
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<24>(ptr));
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedEnumParser<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(_internal_mutable_arg_types(), ptr, ctx, ::baikaldb::pb::PrimitiveType_IsValid, &_internal_metadata_, 3);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .baikaldb.pb.PrimitiveType return_type = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::baikaldb::pb::PrimitiveType_IsValid(val))) {
            _internal_set_return_type(static_cast<::baikaldb::pb::PrimitiveType>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(4, val, mutable_unknown_fields());
          }
        } else
          goto handle_unusual;
        continue;
      // optional bool has_var_args = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          _Internal::set_has_has_var_args(&has_bits);
          has_var_args_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Function::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:baikaldb.pb.Function)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "baikaldb.pb.Function.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // required int32 fn_op = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_fn_op(), target);
  }

  // repeated .baikaldb.pb.PrimitiveType arg_types = 3;
  for (int i = 0, n = this->_internal_arg_types_size(); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
        3, this->_internal_arg_types(i), target);
  }

  // optional .baikaldb.pb.PrimitiveType return_type = 4;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      4, this->_internal_return_type(), target);
  }

  // optional bool has_var_args = 5;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(5, this->_internal_has_var_args(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:baikaldb.pb.Function)
  return target;
}

size_t Function::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:baikaldb.pb.Function)
  size_t total_size = 0;

  if (_internal_has_name()) {
    // required string name = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  if (_internal_has_fn_op()) {
    // required int32 fn_op = 2;
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_fn_op());
  }

  return total_size;
}
size_t Function::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:baikaldb.pb.Function)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required string name = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());

    // required int32 fn_op = 2;
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_fn_op());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .baikaldb.pb.PrimitiveType arg_types = 3;
  {
    size_t data_size = 0;
    unsigned int count = static_cast<unsigned int>(this->_internal_arg_types_size());for (unsigned int i = 0; i < count; i++) {
      data_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(
        this->_internal_arg_types(static_cast<int>(i)));
    }
    total_size += (1UL * count) + data_size;
  }

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000000cu) {
    // optional .baikaldb.pb.PrimitiveType return_type = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_return_type());
    }

    // optional bool has_var_args = 5;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 1;
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Function::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Function::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Function::GetClassData() const { return &_class_data_; }

void Function::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Function *>(to)->MergeFrom(
      static_cast<const Function &>(from));
}


void Function::MergeFrom(const Function& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:baikaldb.pb.Function)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  arg_types_.MergeFrom(from.arg_types_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_name(from._internal_name());
    }
    if (cached_has_bits & 0x00000002u) {
      fn_op_ = from.fn_op_;
    }
    if (cached_has_bits & 0x00000004u) {
      return_type_ = from.return_type_;
    }
    if (cached_has_bits & 0x00000008u) {
      has_var_args_ = from.has_var_args_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Function::CopyFrom(const Function& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:baikaldb.pb.Function)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Function::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  return true;
}

void Function::InternalSwap(Function* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  arg_types_.InternalSwap(&other->arg_types_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &name_, lhs_arena,
      &other->name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Function, has_var_args_)
      + sizeof(Function::has_var_args_)
      - PROTOBUF_FIELD_OFFSET(Function, fn_op_)>(
          reinterpret_cast<char*>(&fn_op_),
          reinterpret_cast<char*>(&other->fn_op_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Function::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_expr_2eproto_getter, &descriptor_table_expr_2eproto_once,
      file_level_metadata_expr_2eproto[0]);
}

// ===================================================================

class DeriveExprNode::_Internal {
 public:
  using HasBits = decltype(std::declval<DeriveExprNode>()._has_bits_);
  static void set_has_tuple_id(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_slot_id(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_int_val(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_double_val(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_string_val(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_bool_val(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_intermediate_slot_id(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
  static void set_has_field_id(HasBits* has_bits) {
    (*has_bits)[0] |= 256u;
  }
  static void set_has_field_name(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_placeholder_id(HasBits* has_bits) {
    (*has_bits)[0] |= 512u;
  }
};

DeriveExprNode::DeriveExprNode(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:baikaldb.pb.DeriveExprNode)
}
DeriveExprNode::DeriveExprNode(const DeriveExprNode& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  string_val_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_string_val()) {
    string_val_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_string_val(), 
      GetArenaForAllocation());
  }
  field_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_field_name()) {
    field_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_field_name(), 
      GetArenaForAllocation());
  }
  ::memcpy(&tuple_id_, &from.tuple_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&placeholder_id_) -
    reinterpret_cast<char*>(&tuple_id_)) + sizeof(placeholder_id_));
  // @@protoc_insertion_point(copy_constructor:baikaldb.pb.DeriveExprNode)
}

void DeriveExprNode::SharedCtor() {
string_val_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
field_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&tuple_id_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&placeholder_id_) -
    reinterpret_cast<char*>(&tuple_id_)) + sizeof(placeholder_id_));
}

DeriveExprNode::~DeriveExprNode() {
  // @@protoc_insertion_point(destructor:baikaldb.pb.DeriveExprNode)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void DeriveExprNode::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  string_val_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  field_name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void DeriveExprNode::ArenaDtor(void* object) {
  DeriveExprNode* _this = reinterpret_cast< DeriveExprNode* >(object);
  (void)_this;
}
void DeriveExprNode::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void DeriveExprNode::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void DeriveExprNode::Clear() {
// @@protoc_insertion_point(message_clear_start:baikaldb.pb.DeriveExprNode)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      string_val_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      field_name_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x000000fcu) {
    ::memset(&tuple_id_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&intermediate_slot_id_) -
        reinterpret_cast<char*>(&tuple_id_)) + sizeof(intermediate_slot_id_));
  }
  if (cached_has_bits & 0x00000300u) {
    ::memset(&field_id_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&placeholder_id_) -
        reinterpret_cast<char*>(&field_id_)) + sizeof(placeholder_id_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DeriveExprNode::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional int32 tuple_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_tuple_id(&has_bits);
          tuple_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional int32 slot_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _Internal::set_has_slot_id(&has_bits);
          slot_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional int64 int_val = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          _Internal::set_has_int_val(&has_bits);
          int_val_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional double double_val = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 33)) {
          _Internal::set_has_double_val(&has_bits);
          double_val_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional bytes string_val = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          auto str = _internal_mutable_string_val();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool bool_val = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          _Internal::set_has_bool_val(&has_bits);
          bool_val_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional int32 intermediate_slot_id = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 56)) {
          _Internal::set_has_intermediate_slot_id(&has_bits);
          intermediate_slot_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional int32 field_id = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 64)) {
          _Internal::set_has_field_id(&has_bits);
          field_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string field_name = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 74)) {
          auto str = _internal_mutable_field_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "baikaldb.pb.DeriveExprNode.field_name");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional int32 placeholder_id = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 80)) {
          _Internal::set_has_placeholder_id(&has_bits);
          placeholder_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* DeriveExprNode::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:baikaldb.pb.DeriveExprNode)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 tuple_id = 1;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_tuple_id(), target);
  }

  // optional int32 slot_id = 2;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_slot_id(), target);
  }

  // optional int64 int_val = 3;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(3, this->_internal_int_val(), target);
  }

  // optional double double_val = 4;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(4, this->_internal_double_val(), target);
  }

  // optional bytes string_val = 5;
  if (cached_has_bits & 0x00000001u) {
    target = stream->WriteBytesMaybeAliased(
        5, this->_internal_string_val(), target);
  }

  // optional bool bool_val = 6;
  if (cached_has_bits & 0x00000040u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(6, this->_internal_bool_val(), target);
  }

  // optional int32 intermediate_slot_id = 7;
  if (cached_has_bits & 0x00000080u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(7, this->_internal_intermediate_slot_id(), target);
  }

  // optional int32 field_id = 8;
  if (cached_has_bits & 0x00000100u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(8, this->_internal_field_id(), target);
  }

  // optional string field_name = 9;
  if (cached_has_bits & 0x00000002u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_field_name().data(), static_cast<int>(this->_internal_field_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "baikaldb.pb.DeriveExprNode.field_name");
    target = stream->WriteStringMaybeAliased(
        9, this->_internal_field_name(), target);
  }

  // optional int32 placeholder_id = 10;
  if (cached_has_bits & 0x00000200u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(10, this->_internal_placeholder_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:baikaldb.pb.DeriveExprNode)
  return target;
}

size_t DeriveExprNode::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:baikaldb.pb.DeriveExprNode)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional bytes string_val = 5;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_string_val());
    }

    // optional string field_name = 9;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_field_name());
    }

    // optional int32 tuple_id = 1;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_tuple_id());
    }

    // optional int32 slot_id = 2;
    if (cached_has_bits & 0x00000008u) {
      total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_slot_id());
    }

    // optional int64 int_val = 3;
    if (cached_has_bits & 0x00000010u) {
      total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64SizePlusOne(this->_internal_int_val());
    }

    // optional double double_val = 4;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 + 8;
    }

    // optional bool bool_val = 6;
    if (cached_has_bits & 0x00000040u) {
      total_size += 1 + 1;
    }

    // optional int32 intermediate_slot_id = 7;
    if (cached_has_bits & 0x00000080u) {
      total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_intermediate_slot_id());
    }

  }
  if (cached_has_bits & 0x00000300u) {
    // optional int32 field_id = 8;
    if (cached_has_bits & 0x00000100u) {
      total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_field_id());
    }

    // optional int32 placeholder_id = 10;
    if (cached_has_bits & 0x00000200u) {
      total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_placeholder_id());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DeriveExprNode::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    DeriveExprNode::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DeriveExprNode::GetClassData() const { return &_class_data_; }

void DeriveExprNode::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<DeriveExprNode *>(to)->MergeFrom(
      static_cast<const DeriveExprNode &>(from));
}


void DeriveExprNode::MergeFrom(const DeriveExprNode& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:baikaldb.pb.DeriveExprNode)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_string_val(from._internal_string_val());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_set_field_name(from._internal_field_name());
    }
    if (cached_has_bits & 0x00000004u) {
      tuple_id_ = from.tuple_id_;
    }
    if (cached_has_bits & 0x00000008u) {
      slot_id_ = from.slot_id_;
    }
    if (cached_has_bits & 0x00000010u) {
      int_val_ = from.int_val_;
    }
    if (cached_has_bits & 0x00000020u) {
      double_val_ = from.double_val_;
    }
    if (cached_has_bits & 0x00000040u) {
      bool_val_ = from.bool_val_;
    }
    if (cached_has_bits & 0x00000080u) {
      intermediate_slot_id_ = from.intermediate_slot_id_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0x00000300u) {
    if (cached_has_bits & 0x00000100u) {
      field_id_ = from.field_id_;
    }
    if (cached_has_bits & 0x00000200u) {
      placeholder_id_ = from.placeholder_id_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DeriveExprNode::CopyFrom(const DeriveExprNode& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:baikaldb.pb.DeriveExprNode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DeriveExprNode::IsInitialized() const {
  return true;
}

void DeriveExprNode::InternalSwap(DeriveExprNode* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &string_val_, lhs_arena,
      &other->string_val_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &field_name_, lhs_arena,
      &other->field_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DeriveExprNode, placeholder_id_)
      + sizeof(DeriveExprNode::placeholder_id_)
      - PROTOBUF_FIELD_OFFSET(DeriveExprNode, tuple_id_)>(
          reinterpret_cast<char*>(&tuple_id_),
          reinterpret_cast<char*>(&other->tuple_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata DeriveExprNode::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_expr_2eproto_getter, &descriptor_table_expr_2eproto_once,
      file_level_metadata_expr_2eproto[1]);
}

// ===================================================================

class ExprNode::_Internal {
 public:
  using HasBits = decltype(std::declval<ExprNode>()._has_bits_);
  static void set_has_node_type(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_col_type(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_num_children(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static const ::baikaldb::pb::Function& fn(const ExprNode* msg);
  static void set_has_fn(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::baikaldb::pb::DeriveExprNode& derive_node(const ExprNode* msg);
  static void set_has_derive_node(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_col_flag(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_charset(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x0000004c) ^ 0x0000004c) != 0;
  }
};

const ::baikaldb::pb::Function&
ExprNode::_Internal::fn(const ExprNode* msg) {
  return *msg->fn_;
}
const ::baikaldb::pb::DeriveExprNode&
ExprNode::_Internal::derive_node(const ExprNode* msg) {
  return *msg->derive_node_;
}
ExprNode::ExprNode(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:baikaldb.pb.ExprNode)
}
ExprNode::ExprNode(const ExprNode& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_fn()) {
    fn_ = new ::baikaldb::pb::Function(*from.fn_);
  } else {
    fn_ = nullptr;
  }
  if (from._internal_has_derive_node()) {
    derive_node_ = new ::baikaldb::pb::DeriveExprNode(*from.derive_node_);
  } else {
    derive_node_ = nullptr;
  }
  ::memcpy(&col_type_, &from.col_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&node_type_) -
    reinterpret_cast<char*>(&col_type_)) + sizeof(node_type_));
  // @@protoc_insertion_point(copy_constructor:baikaldb.pb.ExprNode)
}

void ExprNode::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&fn_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&charset_) -
    reinterpret_cast<char*>(&fn_)) + sizeof(charset_));
node_type_ = 1;
}

ExprNode::~ExprNode() {
  // @@protoc_insertion_point(destructor:baikaldb.pb.ExprNode)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void ExprNode::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete fn_;
  if (this != internal_default_instance()) delete derive_node_;
}

void ExprNode::ArenaDtor(void* object) {
  ExprNode* _this = reinterpret_cast< ExprNode* >(object);
  (void)_this;
}
void ExprNode::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ExprNode::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ExprNode::Clear() {
// @@protoc_insertion_point(message_clear_start:baikaldb.pb.ExprNode)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(fn_ != nullptr);
      fn_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(derive_node_ != nullptr);
      derive_node_->Clear();
    }
  }
  if (cached_has_bits & 0x0000007cu) {
    ::memset(&col_type_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&charset_) -
        reinterpret_cast<char*>(&col_type_)) + sizeof(charset_));
    node_type_ = 1;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ExprNode::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required .baikaldb.pb.ExprNodeType node_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::baikaldb::pb::ExprNodeType_IsValid(val))) {
            _internal_set_node_type(static_cast<::baikaldb::pb::ExprNodeType>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(1, val, mutable_unknown_fields());
          }
        } else
          goto handle_unusual;
        continue;
      // required .baikaldb.pb.PrimitiveType col_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::baikaldb::pb::PrimitiveType_IsValid(val))) {
            _internal_set_col_type(static_cast<::baikaldb::pb::PrimitiveType>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(2, val, mutable_unknown_fields());
          }
        } else
          goto handle_unusual;
        continue;
      // required int32 num_children = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          _Internal::set_has_num_children(&has_bits);
          num_children_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .baikaldb.pb.Function fn = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_fn(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .baikaldb.pb.DeriveExprNode derive_node = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_derive_node(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 col_flag = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          _Internal::set_has_col_flag(&has_bits);
          col_flag_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .baikaldb.pb.Charset charset = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 56)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::baikaldb::pb::Charset_IsValid(val))) {
            _internal_set_charset(static_cast<::baikaldb::pb::Charset>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(7, val, mutable_unknown_fields());
          }
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ExprNode::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:baikaldb.pb.ExprNode)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .baikaldb.pb.ExprNodeType node_type = 1;
  if (cached_has_bits & 0x00000040u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_node_type(), target);
  }

  // required .baikaldb.pb.PrimitiveType col_type = 2;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->_internal_col_type(), target);
  }

  // required int32 num_children = 3;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_num_children(), target);
  }

  // optional .baikaldb.pb.Function fn = 4;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::fn(this), target, stream);
  }

  // optional .baikaldb.pb.DeriveExprNode derive_node = 5;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        5, _Internal::derive_node(this), target, stream);
  }

  // optional uint32 col_flag = 6;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(6, this->_internal_col_flag(), target);
  }

  // optional .baikaldb.pb.Charset charset = 7;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      7, this->_internal_charset(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:baikaldb.pb.ExprNode)
  return target;
}

size_t ExprNode::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:baikaldb.pb.ExprNode)
  size_t total_size = 0;

  if (_internal_has_col_type()) {
    // required .baikaldb.pb.PrimitiveType col_type = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_col_type());
  }

  if (_internal_has_num_children()) {
    // required int32 num_children = 3;
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_num_children());
  }

  if (_internal_has_node_type()) {
    // required .baikaldb.pb.ExprNodeType node_type = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_node_type());
  }

  return total_size;
}
size_t ExprNode::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:baikaldb.pb.ExprNode)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x0000004c) ^ 0x0000004c) == 0) {  // All required fields are present.
    // required .baikaldb.pb.PrimitiveType col_type = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_col_type());

    // required int32 num_children = 3;
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_num_children());

    // required .baikaldb.pb.ExprNodeType node_type = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_node_type());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional .baikaldb.pb.Function fn = 4;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *fn_);
    }

    // optional .baikaldb.pb.DeriveExprNode derive_node = 5;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *derive_node_);
    }

  }
  if (cached_has_bits & 0x00000030u) {
    // optional uint32 col_flag = 6;
    if (cached_has_bits & 0x00000010u) {
      total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_col_flag());
    }

    // optional .baikaldb.pb.Charset charset = 7;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_charset());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ExprNode::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ExprNode::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ExprNode::GetClassData() const { return &_class_data_; }

void ExprNode::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ExprNode *>(to)->MergeFrom(
      static_cast<const ExprNode &>(from));
}


void ExprNode::MergeFrom(const ExprNode& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:baikaldb.pb.ExprNode)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_mutable_fn()->::baikaldb::pb::Function::MergeFrom(from._internal_fn());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_mutable_derive_node()->::baikaldb::pb::DeriveExprNode::MergeFrom(from._internal_derive_node());
    }
    if (cached_has_bits & 0x00000004u) {
      col_type_ = from.col_type_;
    }
    if (cached_has_bits & 0x00000008u) {
      num_children_ = from.num_children_;
    }
    if (cached_has_bits & 0x00000010u) {
      col_flag_ = from.col_flag_;
    }
    if (cached_has_bits & 0x00000020u) {
      charset_ = from.charset_;
    }
    if (cached_has_bits & 0x00000040u) {
      node_type_ = from.node_type_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ExprNode::CopyFrom(const ExprNode& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:baikaldb.pb.ExprNode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExprNode::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  if (_internal_has_fn()) {
    if (!fn_->IsInitialized()) return false;
  }
  return true;
}

void ExprNode::InternalSwap(ExprNode* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ExprNode, charset_)
      + sizeof(ExprNode::charset_)
      - PROTOBUF_FIELD_OFFSET(ExprNode, fn_)>(
          reinterpret_cast<char*>(&fn_),
          reinterpret_cast<char*>(&other->fn_));
  swap(node_type_, other->node_type_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ExprNode::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_expr_2eproto_getter, &descriptor_table_expr_2eproto_once,
      file_level_metadata_expr_2eproto[2]);
}

// ===================================================================

class Expr::_Internal {
 public:
  using HasBits = decltype(std::declval<Expr>()._has_bits_);
  static void set_has_database(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_table(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

Expr::Expr(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  nodes_(arena),
  index_ids_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:baikaldb.pb.Expr)
}
Expr::Expr(const Expr& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_),
      nodes_(from.nodes_),
      index_ids_(from.index_ids_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  database_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_database()) {
    database_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_database(), 
      GetArenaForAllocation());
  }
  table_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_table()) {
    table_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_table(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:baikaldb.pb.Expr)
}

void Expr::SharedCtor() {
database_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
table_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

Expr::~Expr() {
  // @@protoc_insertion_point(destructor:baikaldb.pb.Expr)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Expr::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  database_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  table_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void Expr::ArenaDtor(void* object) {
  Expr* _this = reinterpret_cast< Expr* >(object);
  (void)_this;
}
void Expr::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Expr::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Expr::Clear() {
// @@protoc_insertion_point(message_clear_start:baikaldb.pb.Expr)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  nodes_.Clear();
  index_ids_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      database_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      table_.ClearNonDefaultToEmpty();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Expr::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .baikaldb.pb.ExprNode nodes = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_nodes(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated int64 index_ids = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ptr -= 1;
          do {
            ptr += 1;
            _internal_add_index_ids(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<16>(ptr));
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt64Parser(_internal_mutable_index_ids(), ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string database = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_database();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "baikaldb.pb.Expr.database");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string table = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_table();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "baikaldb.pb.Expr.table");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Expr::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:baikaldb.pb.Expr)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .baikaldb.pb.ExprNode nodes = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_nodes_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_nodes(i), target, stream);
  }

  // repeated int64 index_ids = 2;
  for (int i = 0, n = this->_internal_index_ids_size(); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(2, this->_internal_index_ids(i), target);
  }

  cached_has_bits = _has_bits_[0];
  // optional string database = 3;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_database().data(), static_cast<int>(this->_internal_database().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "baikaldb.pb.Expr.database");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_database(), target);
  }

  // optional string table = 4;
  if (cached_has_bits & 0x00000002u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_table().data(), static_cast<int>(this->_internal_table().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "baikaldb.pb.Expr.table");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_table(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:baikaldb.pb.Expr)
  return target;
}

size_t Expr::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:baikaldb.pb.Expr)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .baikaldb.pb.ExprNode nodes = 1;
  total_size += 1UL * this->_internal_nodes_size();
  for (const auto& msg : this->nodes_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated int64 index_ids = 2;
  {
    size_t data_size = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      Int64Size(this->index_ids_);
    total_size += 1 *
                  ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_index_ids_size());
    total_size += data_size;
  }

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional string database = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_database());
    }

    // optional string table = 4;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_table());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Expr::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Expr::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Expr::GetClassData() const { return &_class_data_; }

void Expr::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Expr *>(to)->MergeFrom(
      static_cast<const Expr &>(from));
}


void Expr::MergeFrom(const Expr& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:baikaldb.pb.Expr)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  nodes_.MergeFrom(from.nodes_);
  index_ids_.MergeFrom(from.index_ids_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_database(from._internal_database());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_set_table(from._internal_table());
    }
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Expr::CopyFrom(const Expr& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:baikaldb.pb.Expr)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Expr::IsInitialized() const {
  if (!::PROTOBUF_NAMESPACE_ID::internal::AllAreInitialized(nodes_)) return false;
  return true;
}

void Expr::InternalSwap(Expr* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  nodes_.InternalSwap(&other->nodes_);
  index_ids_.InternalSwap(&other->index_ids_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &database_, lhs_arena,
      &other->database_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &table_, lhs_arena,
      &other->table_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Expr::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_expr_2eproto_getter, &descriptor_table_expr_2eproto_once,
      file_level_metadata_expr_2eproto[3]);
}

// ===================================================================

class Exprs::_Internal {
 public:
};

Exprs::Exprs(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  exprs_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:baikaldb.pb.Exprs)
}
Exprs::Exprs(const Exprs& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      exprs_(from.exprs_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:baikaldb.pb.Exprs)
}

void Exprs::SharedCtor() {
}

Exprs::~Exprs() {
  // @@protoc_insertion_point(destructor:baikaldb.pb.Exprs)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Exprs::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Exprs::ArenaDtor(void* object) {
  Exprs* _this = reinterpret_cast< Exprs* >(object);
  (void)_this;
}
void Exprs::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Exprs::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Exprs::Clear() {
// @@protoc_insertion_point(message_clear_start:baikaldb.pb.Exprs)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  exprs_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Exprs::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .baikaldb.pb.Expr exprs = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_exprs(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Exprs::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:baikaldb.pb.Exprs)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .baikaldb.pb.Expr exprs = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_exprs_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_exprs(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:baikaldb.pb.Exprs)
  return target;
}

size_t Exprs::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:baikaldb.pb.Exprs)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .baikaldb.pb.Expr exprs = 1;
  total_size += 1UL * this->_internal_exprs_size();
  for (const auto& msg : this->exprs_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Exprs::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Exprs::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Exprs::GetClassData() const { return &_class_data_; }

void Exprs::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Exprs *>(to)->MergeFrom(
      static_cast<const Exprs &>(from));
}


void Exprs::MergeFrom(const Exprs& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:baikaldb.pb.Exprs)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  exprs_.MergeFrom(from.exprs_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Exprs::CopyFrom(const Exprs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:baikaldb.pb.Exprs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Exprs::IsInitialized() const {
  if (!::PROTOBUF_NAMESPACE_ID::internal::AllAreInitialized(exprs_)) return false;
  return true;
}

void Exprs::InternalSwap(Exprs* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  exprs_.InternalSwap(&other->exprs_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Exprs::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_expr_2eproto_getter, &descriptor_table_expr_2eproto_once,
      file_level_metadata_expr_2eproto[4]);
}

// ===================================================================

class ColumnDdlInfo::_Internal {
 public:
  using HasBits = decltype(std::declval<ColumnDdlInfo>()._has_bits_);
  static void set_has_opt_sql(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

void ColumnDdlInfo::clear_update_slots() {
  update_slots_.Clear();
}
void ColumnDdlInfo::clear_tuples() {
  tuples_.Clear();
}
ColumnDdlInfo::ColumnDdlInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  update_exprs_(arena),
  update_slots_(arena),
  scan_conjuncts_(arena),
  tuples_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:baikaldb.pb.ColumnDdlInfo)
}
ColumnDdlInfo::ColumnDdlInfo(const ColumnDdlInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_),
      update_exprs_(from.update_exprs_),
      update_slots_(from.update_slots_),
      scan_conjuncts_(from.scan_conjuncts_),
      tuples_(from.tuples_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  opt_sql_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_opt_sql()) {
    opt_sql_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_opt_sql(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:baikaldb.pb.ColumnDdlInfo)
}

void ColumnDdlInfo::SharedCtor() {
opt_sql_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

ColumnDdlInfo::~ColumnDdlInfo() {
  // @@protoc_insertion_point(destructor:baikaldb.pb.ColumnDdlInfo)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void ColumnDdlInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  opt_sql_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ColumnDdlInfo::ArenaDtor(void* object) {
  ColumnDdlInfo* _this = reinterpret_cast< ColumnDdlInfo* >(object);
  (void)_this;
}
void ColumnDdlInfo::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ColumnDdlInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ColumnDdlInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:baikaldb.pb.ColumnDdlInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  update_exprs_.Clear();
  update_slots_.Clear();
  scan_conjuncts_.Clear();
  tuples_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    opt_sql_.ClearNonDefaultToEmpty();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ColumnDdlInfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .baikaldb.pb.Expr update_exprs = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_update_exprs(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .baikaldb.pb.SlotDescriptor update_slots = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_update_slots(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .baikaldb.pb.Expr scan_conjuncts = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_scan_conjuncts(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .baikaldb.pb.TupleDescriptor tuples = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_tuples(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      // optional string opt_sql = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          auto str = _internal_mutable_opt_sql();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "baikaldb.pb.ColumnDdlInfo.opt_sql");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ColumnDdlInfo::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:baikaldb.pb.ColumnDdlInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .baikaldb.pb.Expr update_exprs = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_update_exprs_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_update_exprs(i), target, stream);
  }

  // repeated .baikaldb.pb.SlotDescriptor update_slots = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_update_slots_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_update_slots(i), target, stream);
  }

  // repeated .baikaldb.pb.Expr scan_conjuncts = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_scan_conjuncts_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, this->_internal_scan_conjuncts(i), target, stream);
  }

  // repeated .baikaldb.pb.TupleDescriptor tuples = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_tuples_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, this->_internal_tuples(i), target, stream);
  }

  cached_has_bits = _has_bits_[0];
  // optional string opt_sql = 5;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_opt_sql().data(), static_cast<int>(this->_internal_opt_sql().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "baikaldb.pb.ColumnDdlInfo.opt_sql");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_opt_sql(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:baikaldb.pb.ColumnDdlInfo)
  return target;
}

size_t ColumnDdlInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:baikaldb.pb.ColumnDdlInfo)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .baikaldb.pb.Expr update_exprs = 1;
  total_size += 1UL * this->_internal_update_exprs_size();
  for (const auto& msg : this->update_exprs_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .baikaldb.pb.SlotDescriptor update_slots = 2;
  total_size += 1UL * this->_internal_update_slots_size();
  for (const auto& msg : this->update_slots_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .baikaldb.pb.Expr scan_conjuncts = 3;
  total_size += 1UL * this->_internal_scan_conjuncts_size();
  for (const auto& msg : this->scan_conjuncts_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .baikaldb.pb.TupleDescriptor tuples = 4;
  total_size += 1UL * this->_internal_tuples_size();
  for (const auto& msg : this->tuples_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // optional string opt_sql = 5;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_opt_sql());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ColumnDdlInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ColumnDdlInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ColumnDdlInfo::GetClassData() const { return &_class_data_; }

void ColumnDdlInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ColumnDdlInfo *>(to)->MergeFrom(
      static_cast<const ColumnDdlInfo &>(from));
}


void ColumnDdlInfo::MergeFrom(const ColumnDdlInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:baikaldb.pb.ColumnDdlInfo)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  update_exprs_.MergeFrom(from.update_exprs_);
  update_slots_.MergeFrom(from.update_slots_);
  scan_conjuncts_.MergeFrom(from.scan_conjuncts_);
  tuples_.MergeFrom(from.tuples_);
  if (from._internal_has_opt_sql()) {
    _internal_set_opt_sql(from._internal_opt_sql());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ColumnDdlInfo::CopyFrom(const ColumnDdlInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:baikaldb.pb.ColumnDdlInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ColumnDdlInfo::IsInitialized() const {
  if (!::PROTOBUF_NAMESPACE_ID::internal::AllAreInitialized(update_exprs_)) return false;
  if (!::PROTOBUF_NAMESPACE_ID::internal::AllAreInitialized(update_slots_)) return false;
  if (!::PROTOBUF_NAMESPACE_ID::internal::AllAreInitialized(scan_conjuncts_)) return false;
  if (!::PROTOBUF_NAMESPACE_ID::internal::AllAreInitialized(tuples_)) return false;
  return true;
}

void ColumnDdlInfo::InternalSwap(ColumnDdlInfo* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  update_exprs_.InternalSwap(&other->update_exprs_);
  update_slots_.InternalSwap(&other->update_slots_);
  scan_conjuncts_.InternalSwap(&other->scan_conjuncts_);
  tuples_.InternalSwap(&other->tuples_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &opt_sql_, lhs_arena,
      &other->opt_sql_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata ColumnDdlInfo::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_expr_2eproto_getter, &descriptor_table_expr_2eproto_once,
      file_level_metadata_expr_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace pb
}  // namespace baikaldb
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::baikaldb::pb::Function* Arena::CreateMaybeMessage< ::baikaldb::pb::Function >(Arena* arena) {
  return Arena::CreateMessageInternal< ::baikaldb::pb::Function >(arena);
}
template<> PROTOBUF_NOINLINE ::baikaldb::pb::DeriveExprNode* Arena::CreateMaybeMessage< ::baikaldb::pb::DeriveExprNode >(Arena* arena) {
  return Arena::CreateMessageInternal< ::baikaldb::pb::DeriveExprNode >(arena);
}
template<> PROTOBUF_NOINLINE ::baikaldb::pb::ExprNode* Arena::CreateMaybeMessage< ::baikaldb::pb::ExprNode >(Arena* arena) {
  return Arena::CreateMessageInternal< ::baikaldb::pb::ExprNode >(arena);
}
template<> PROTOBUF_NOINLINE ::baikaldb::pb::Expr* Arena::CreateMaybeMessage< ::baikaldb::pb::Expr >(Arena* arena) {
  return Arena::CreateMessageInternal< ::baikaldb::pb::Expr >(arena);
}
template<> PROTOBUF_NOINLINE ::baikaldb::pb::Exprs* Arena::CreateMaybeMessage< ::baikaldb::pb::Exprs >(Arena* arena) {
  return Arena::CreateMessageInternal< ::baikaldb::pb::Exprs >(arena);
}
template<> PROTOBUF_NOINLINE ::baikaldb::pb::ColumnDdlInfo* Arena::CreateMaybeMessage< ::baikaldb::pb::ColumnDdlInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::baikaldb::pb::ColumnDdlInfo >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
