// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: optype.proto

#include "optype.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace baikaldb {
namespace pb {
}  // namespace pb
}  // namespace baikaldb
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_optype_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_optype_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_optype_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_optype_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014optype.proto\022\013baikaldb.pb*\354\032\n\006OpType\022\013"
  "\n\007OP_NONE\020\000\022\r\n\tOP_INSERT\020\001\022\r\n\tOP_DELETE\020"
  "\002\022\r\n\tOP_UPDATE\020\003\022\r\n\tOP_SELECT\020\004\022\014\n\010OP_BE"
  "GIN\020\005\022\r\n\tOP_COMMIT\020\006\022\017\n\013OP_ROLLBACK\020\007\022\013\n"
  "\007OP_KILL\020\010\022\022\n\016OP_START_SPLIT\020\t\022\033\n\027OP_STA"
  "RT_SPLIT_FOR_TAIL\020\n\022\037\n\033OP_VALIDATE_AND_A"
  "DD_VERSION\020\013\022#\n\037OP_ADD_VERSION_FOR_SPLIT"
  "_REGION\020\014\022\025\n\021OP_TRUNCATE_TABLE\020\r\022\016\n\nOP_P"
  "REPARE\020\016\022\016\n\nOP_EXPLAIN\020\017\022 \n\034OP_ADJUSTKEY"
  "_AND_ADD_VERSION\020\020\022\020\n\014OP_START_DDL\020\021\022\037\n\033"
  "OP_START_DDL_FOR_DROP_INDEX\020\022\022\033\n\027OP_UPDA"
  "TE_STORE_DDLWORK\020\023\022\017\n\013OP_KV_BATCH\020\024\022\r\n\tO"
  "P_PUT_KV\020\025\022\020\n\014OP_DELETE_KV\020\026\022\025\n\021OP_KV_BA"
  "TCH_SPLIT\020\027\022\037\n\033OP_TXN_QUERY_PRIMARY_REGI"
  "ON\020\030\022\026\n\022OP_TXN_QUERY_STATE\020\031\022\023\n\017OP_TXN_C"
  "OMPLETE\020\032\022\031\n\025OP_CLEAR_APPLYING_TXN\020\033\022\030\n\024"
  "OP_SELECT_FOR_UPDATE\020\034\022\017\n\013OP_MERGE_KV\020\035\022"
  "\014\n\010OP_UNION\0203\022\013\n\007OP_LOAD\0204\022\037\n\033OP_UPDATE_"
  "PRIMARY_TIMESTAMP\0205\022\027\n\023OP_PARTIAL_ROLLBA"
  "CK\0206\022\022\n\016OP_READ_BINLOG\020<\022\026\n\022OP_PREWRITE_"
  "BINLOG\020=\022\024\n\020OP_COMMIT_BINLOG\020>\022\026\n\022OP_ROL"
  "LBACK_BINLOG\020\?\022\022\n\016OP_FAKE_BINLOG\020@\022\025\n\021OP"
  "_RECOVER_BINLOG\020A\022\023\n\017OP_QUERY_BINLOG\020B\022\034"
  "\n\030OP_UPDATE_OFFLINE_BINLOG\020C\022\033\n\027OP_QUERY"
  "_OFFLINE_BINLOG\020D\022\035\n\031OP_RECOVER_OFFLINE_"
  "BINLOG\020E\022\020\n\014OP_OLAP_INFO\020P\022\026\n\022OP_OLAP_IN"
  "DEX_INFO\020Q\022\031\n\025OP_ROLLUP_REGION_INIT\020R\022\033\n"
  "\027OP_ROLLUP_REGION_FINISH\020S\022\033\n\027OP_ROLLUP_"
  "REGION_FAILED\020T\022\033\n\027OP_ROLLUP_CLEAR_VERSI"
  "ON\020U\022\022\n\016OP_COLUMN_INFO\020V\022\022\n\016OP_REDIS_WRI"
  "TE\020Z\022\022\n\016OP_ADD_LOGICAL\020r\022\023\n\017OP_ADD_PHYSI"
  "CAL\020s\022\023\n\017OP_ADD_INSTANCE\020t\022\023\n\017OP_DROP_LO"
  "GICAL\020u\022\024\n\020OP_DROP_PHYSICAL\020v\022\024\n\020OP_DROP"
  "_INSTANCE\020w\022\026\n\022OP_UPDATE_INSTANCE\020x\022\024\n\020O"
  "P_MOVE_PHYSICAL\020y\022\022\n\016OP_CREATE_USER\020z\022\024\n"
  "\020OP_ADD_PRIVILEGE\020{\022\020\n\014OP_DROP_USER\020|\022\025\n"
  "\021OP_DROP_PRIVILEGE\020}\022\027\n\023OP_CREATE_NAMESP"
  "ACE\020~\022\026\n\022OP_CREATE_DATABASE\020\177\022\024\n\017OP_CREA"
  "TE_TABLE\020\200\001\022\026\n\021OP_DROP_NAMESPACE\020\201\001\022\025\n\020O"
  "P_DROP_DATABASE\020\202\001\022\022\n\rOP_DROP_TABLE\020\203\001\022\024"
  "\n\017OP_RENAME_TABLE\020\204\001\022\021\n\014OP_ADD_FIELD\020\205\001\022"
  "\021\n\014OP_ADD_INDEX\020\206\001\022\022\n\rOP_DROP_INDEX\020\207\001\022\022"
  "\n\rOP_DROP_FIELD\020\210\001\022\024\n\017OP_RENAME_FIELD\020\211\001"
  "\022\024\n\017OP_RENAME_INDEX\020\212\001\022\024\n\017OP_MODIFY_FIEL"
  "D\020\213\001\022\030\n\023OP_MODIFY_NAMESPACE\020\214\001\022\027\n\022OP_MOD"
  "IFY_DATABASE\020\215\001\022\025\n\020OP_UPDATE_REGION\020\216\001\022\023"
  "\n\016OP_DROP_REGION\020\217\001\022\024\n\017OP_SPLIT_REGION\020\220"
  "\001\022\030\n\023OP_UPDATE_BYTE_SIZE\020\221\001\022!\n\034OP_GEN_ID"
  "_FOR_AUTO_INCREMENT\020\222\001\022!\n\034OP_UPDATE_FOR_"
  "AUTO_INCREMENT\020\223\001\022\026\n\021OP_RESTORE_REGION\020\224"
  "\001\022\034\n\027OP_OPEN_UNSAFE_DECISION\020\225\001\022\034\n\027OP_SE"
  "T_INSTANCE_MIGRATE\020\226\001\022!\n\034OP_ADD_ID_FOR_A"
  "UTO_INCREMENT\020\230\001\022\"\n\035OP_DROP_ID_FOR_AUTO_"
  "INCREMENT\020\231\001\022\032\n\025OP_CLOSE_LOAD_BALANCE\020\232\001"
  "\022\031\n\024OP_OPEN_LOAD_BALANCE\020\233\001\022\035\n\030OP_CLOSE_"
  "UNSAFE_DECISION\020\234\001\022\024\n\017OP_UPDATE_DISTS\020\235\001"
  "\022\025\n\020OP_CLOSE_MIGRATE\020\236\001\022\024\n\017OP_OPEN_MIGRA"
  "TE\020\237\001\022\032\n\025OP_UPDATE_SPLIT_LINES\020\240\001\022\033\n\026OP_"
  "SET_INSTANCE_STATUS\020\241\001\022\033\n\026OP_MODIFY_RESO"
  "URCE_TAG\020\243\001\022\024\n\017OP_MERGE_REGION\020\244\001\022\033\n\026OP_"
  "UPDATE_MERGE_SWITCH\020\245\001\022\033\n\026OP_UPDATE_INDE"
  "X_STATUS\020\246\001\022\026\n\021OP_DELETE_DDLWORK\020\247\001\022\032\n\025O"
  "P_UPDATE_SCHEMA_CONF\020\250\001\022\025\n\020OP_RESTORE_TA"
  "BLE\020\251\001\022\034\n\027OP_DROP_TABLE_TOMBSTONE\020\252\001\022\033\n\026"
  "OP_RECOVERY_ALL_REGION\020\253\001\022\031\n\024OP_UPDATE_S"
  "TATISTICS\020\254\001\022\017\n\nOP_GEN_TSO\020\255\001\022\021\n\014OP_RESE"
  "T_TSO\020\256\001\022\022\n\rOP_UPDATE_TSO\020\257\001\022\026\n\021OP_QUERY"
  "_TSO_INFO\020\260\001\022\023\n\016OP_LINK_BINLOG\020\261\001\022\025\n\020OP_"
  "UNLINK_BINLOG\020\262\001\022\035\n\030OP_SET_INDEX_HINT_ST"
  "ATUS\020\263\001\022\033\n\026OP_UPDATE_TTL_DURATION\020\264\001\022\035\n\030"
  "OP_UPDATE_INSTANCE_PARAM\020\265\001\022$\n\037OP_UPDATE"
  "_INDEX_REGION_DDL_WORK\020\266\001\022\030\n\023OP_SUSPEND_"
  "DDL_WORK\020\267\001\022\030\n\023OP_RESTART_DDL_WORK\020\270\001\022 \n"
  "\033OP_REMOVE_GLOBAL_INDEX_DATA\020\271\001\022 \n\033OP_UP"
  "DATE_MAIN_LOGICAL_ROOM\020\272\001\022\023\n\016OP_ADD_LEAR"
  "NER\020\273\001\022\024\n\017OP_DROP_LEARNER\020\274\001\022$\n\037OP_OPEN_"
  "NETWORK_SEGMENT_BALANCE\020\275\001\022%\n OP_CLOSE_N"
  "ETWORK_SEGMENT_BALANCE\020\276\001\022\034\n\027OP_UPDATE_T"
  "ABLE_COMMENT\020\277\001\022\022\n\rOP_SWAP_TABLE\020\300\001\022\030\n\023O"
  "P_MODIFY_PARTITION\020\301\001\022\026\n\021OP_UPDATE_CHARS"
  "ET\020\302\001\022\025\n\020OP_ADD_PARTITION\020\303\001\022\026\n\021OP_DROP_"
  "PARTITION\020\304\001\022%\n OP_UPDATE_DYNAMIC_PARTIT"
  "ION_ATTR\020\305\001\022\031\n\024OP_DROP_PARTITION_TS\020\306\001\022\032"
  "\n\025OP_SPECIFY_SPLIT_KEYS\020\307\001\022\031\n\024OP_CONVERT"
  "_PARTITION\020\310\001\022\023\n\016OP_MODIFY_USER\020\311\001\022\023\n\016OP"
  "_CREATE_VIEW\020\312\001\022\021\n\014OP_DROP_VIEW\020\313\001\022\036\n\031OP"
  "_DROP_INVALID_PRIVILEGE\020\314\001"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_optype_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_optype_2eproto = {
  false, false, 3466, descriptor_table_protodef_optype_2eproto, "optype.proto", 
  &descriptor_table_optype_2eproto_once, nullptr, 0, 0,
  schemas, file_default_instances, TableStruct_optype_2eproto::offsets,
  nullptr, file_level_enum_descriptors_optype_2eproto, file_level_service_descriptors_optype_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_optype_2eproto_getter() {
  return &descriptor_table_optype_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_optype_2eproto(&descriptor_table_optype_2eproto);
namespace baikaldb {
namespace pb {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* OpType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_optype_2eproto);
  return file_level_enum_descriptors_optype_2eproto[0];
}
bool OpType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 28:
    case 29:
    case 51:
    case 52:
    case 53:
    case 54:
    case 60:
    case 61:
    case 62:
    case 63:
    case 64:
    case 65:
    case 66:
    case 67:
    case 68:
    case 69:
    case 80:
    case 81:
    case 82:
    case 83:
    case 84:
    case 85:
    case 86:
    case 90:
    case 114:
    case 115:
    case 116:
    case 117:
    case 118:
    case 119:
    case 120:
    case 121:
    case 122:
    case 123:
    case 124:
    case 125:
    case 126:
    case 127:
    case 128:
    case 129:
    case 130:
    case 131:
    case 132:
    case 133:
    case 134:
    case 135:
    case 136:
    case 137:
    case 138:
    case 139:
    case 140:
    case 141:
    case 142:
    case 143:
    case 144:
    case 145:
    case 146:
    case 147:
    case 148:
    case 149:
    case 150:
    case 152:
    case 153:
    case 154:
    case 155:
    case 156:
    case 157:
    case 158:
    case 159:
    case 160:
    case 161:
    case 163:
    case 164:
    case 165:
    case 166:
    case 167:
    case 168:
    case 169:
    case 170:
    case 171:
    case 172:
    case 173:
    case 174:
    case 175:
    case 176:
    case 177:
    case 178:
    case 179:
    case 180:
    case 181:
    case 182:
    case 183:
    case 184:
    case 185:
    case 186:
    case 187:
    case 188:
    case 189:
    case 190:
    case 191:
    case 192:
    case 193:
    case 194:
    case 195:
    case 196:
    case 197:
    case 198:
    case 199:
    case 200:
    case 201:
    case 202:
    case 203:
    case 204:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace pb
}  // namespace baikaldb
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
